# Project Workflow Overview:
1. Import Libraries
2. Load DataFrame
3. Clean DataFrame
    <br>
    3.1 Convert Time Format
    <br>
    3.2 Clean **Actor** Field
    <br> 
    3.3 Clean **Filename** Field 
4. Anonymize Data

## Import Libraries

In [1]:
import sys
sys.path.append('../') # these two lines allow the notebook to find the path to the source code contained in 'src'
import pandas as pd
import re
import io_utils, data_cleaning, data_anonymization
#from tests import test_preprocessing, test_anonymization
from src.data.constants import INTERIM_DATA_DIR

## Load DataFrame
- Use functions in file **io_utils.py.py**
- The csv file is the output of process_raw_data

In [2]:
df = io_utils.reading_dataframe(dir= INTERIM_DATA_DIR, file_name='traces250102_clean.csv')

Directory is ok.

### Print 5 rows and columns of dataframe

In [3]:
df.head()

,research_usage,result,_id.$oid,timestamp.$date,stored.$date,actor,actor.objectType,verb,object,object.objectType,...,P_codeState,filename,F_codeState,Debug_TimeStampEnd,Debug_TimeStampActions,tests,function,time_delta,session.duration,seance
0,1.0,NaN,675aa485a7dff6d2d4811b45,2024-12-12 09:53:24.624000+00:00,2024-11-27T10:57:29.801Z,abaly.oura.etu/,Agent,Session.Start,https://www.cristal.univ-lille.fr/objects/Session,Activity,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7 days 00:05:05.313000,NaN,CTP
1,1.0,NaN,675aa4cea7dff6d2d4811b4f,2024-12-12 09:53:25.008000+00:00,2024-11-27T10:57:29.801Z,abaly.oura.etu/,Agent,File.Open,https://www.cristal.univ-lille.fr/objects/File,Activity,...,NaN,/home/l1/abaly.oura.etu/Downloads/puissance4.py,"# Compléter ici (noms, groupe, contenu fichier...",NaN,NaN,NaN,NaN,0 days 00:00:00.384000,NaN,CTP
2,1.0,NaN,675aa4cea7dff6d2d4811b50,2024-12-12 09:54:38.793000+00:00,2024-11-27T10:57:29.801Z,abaly.oura.etu/,Agent,Session.End,https://www.cristal.univ-lille.fr/objects/Session,Activity,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0 days 00:01:13.785000,0 days 00:01:14.169000,CTP
3,1.0,NaN,671b54aabd5a98b8f9dc8c14,2024-10-25 10:19:54.344000+00:00,2024-08-29T07:34:11.687Z,abaly.oura.etu/,Agent,Session.Start,https://www.cristal.univ-lille.fr/objects/Session,Activity,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 days 00:21:30.977000,NaN,semaine_8
4,1.0,NaN,671b54f6bd5a98b8f9dc8c45,2024-10-25 10:19:54.583000+00:00,2024-08-29T07:34:11.687Z,abaly.oura.etu/,Agent,File.Open,https://www.cristal.univ-lille.fr/objects/File,Activity,...,NaN,/home/l1/abaly.oura.etu/TDM 8/devinette.py,# L1 MI S1 - Prog\n# TP exos de manipulation -...,NaN,NaN,NaN,NaN,0 days 00:00:00.239000,NaN,semaine_8

## Clean DataFrame

### Convert Time Format

In [4]:
# Before
df[['session.id', 'timestamp.$date', 'time_delta', 'session.duration']]

,session.id,timestamp.$date,time_delta,session.duration
0,139682817762848,2024-12-12 09:53:24.624000+00:00,7 days 00:05:05.313000,NaN
1,139682817762848,2024-12-12 09:53:25.008000+00:00,0 days 00:00:00.384000,NaN
2,139682817762848,2024-12-12 09:54:38.793000+00:00,0 days 00:01:13.785000,0 days 00:01:14.169000
3,139779362711072,2024-10-25 10:19:54.344000+00:00,1 days 00:21:30.977000,NaN
4,139779362711072,2024-10-25 10:19:54.583000+00:00,0 days 00:00:00.239000,NaN
...,...,...,...,...
306941,139911616626448,2024-09-04 14:16:21.990000+00:00,0 days 00:00:53.790000,NaN
306942,139911616626448,2024-09-04 14:18:08.724000+00:00,0 days 00:01:46.734000,NaN
306943,139911616626448,2024-09-04 14:18:08.725000+00:00,0 days 00:00:00.001000,0 days 00:22:32.511000
306944,140578214641424,2024-09-04 13:29:54.300000+00:00,0 days 00:00:00,NaN
306945,140578214641424,2024-09-04 13:33:55.593000+00:00,0 days 00:04:01.293000,0 days 00:04:01.293000

In [5]:
# Apply
df = data_cleaning.clean_time(df)

In [6]:
# After
df[['session.id', 'timestamp.$date', 'time_delta', 'session.duration']]

,session.id,timestamp.$date,time_delta,session.duration
0,139682817762848,2024-12-12 09:53:24.624000+00:00,7 days 00:05:05.313000,NaN
1,139682817762848,2024-12-12 09:53:25.008000+00:00,0 days 00:00:00.384000,NaN
2,139682817762848,2024-12-12 09:54:38.793000+00:00,0 days 00:01:13.785000,0 days 00:01:14.169000
3,139779362711072,2024-10-25 10:19:54.344000+00:00,1 days 00:21:30.977000,NaN
4,139779362711072,2024-10-25 10:19:54.583000+00:00,0 days 00:00:00.239000,NaN
...,...,...,...,...
306941,139911616626448,2024-09-04 14:16:21.990000+00:00,0 days 00:00:53.790000,NaN
306942,139911616626448,2024-09-04 14:18:08.724000+00:00,0 days 00:01:46.734000,NaN
306943,139911616626448,2024-09-04 14:18:08.725000+00:00,0 days 00:00:00.001000,0 days 00:22:32.511000
306944,140578214641424,2024-09-04 13:29:54.300000+00:00,0 days 00:00:00,NaN
306945,140578214641424,2024-09-04 13:33:55.593000+00:00,0 days 00:04:01.293000,0 days 00:04:01.293000

### Clean **Actor** Field
Process: 
1. Extract all the non matching name of actor with prenom.nom.etu -> **incorrect = not_a_correct_identifier()**
2. Delete emails at the end -> **df = delete_end_email()**
3. Delete all rows of nebut -> **df = delete_actor_lines()**
4. Split actor and binome into 2 columns -> **df = split_actor_binome()**
5. Remove actors or binomes name -> **df = delete_name_actor_binome()**
6. Replace None value by " " -> **df = replace_None_by_str()**
7. Replace joker -> **df = replace_jokers()**
8. Cleaning manually -> **df = cleaning_manual_actors_2425()**

#### 1. Extract all the non matching name of actor with prenom.nom.etu

In [7]:
incorrect = data_cleaning.not_a_correct_identifier(df)
incorrect

0                                   abaly.oura.etu/
1                     abaly.oura.etu@univ-lille.fr/
2                      abdallah.saint-ghislain.etu/
3                    abdelrahmane.bendjeladjel.etu/
4                            abderrahmen.ayadi.etu/
                           ...
527                             youssef.airaki.etu/
528                               yves.djegnon.etu/
529    yves.djegnon.etu/fatoumata-bintou.traore.etu
530                             zacharie.deroo.etu/
531           zacharie.deroo.etu/noe.carpentier.etu
Length: 532, dtype: object

#### 2. Delete the email at the end

In [8]:
## Before deleting
print(df['actor'].unique())

['abaly.oura.etu/' 'abaly.oura.etu@univ-lille.fr/'
 'abdallah.saint-ghislain.etu/' 'abdelrahmane.bendjeladjel.etu/'
 'abderrahmen.ayadi.etu/' 'abderrahmen.ayadi.etu/abderrahmen.ayadi.etu'
 'abderrahmen.ayadi.etu/hazem.hlioui.etu' 'abdoulaye.mbaye.etu/'
 'abdoulaye.nguere.etu/' 'abdoulaye.nguere.etu/serigne.cisse.etu'
 'adam.chikh-touami.etu/' 'adam.chikh-touami.etu/ilian.briki.etu'
 'adam.oukzedou.etu/' 'adam.sialiti.etu/' 'adama-eliya.avlah.etu/'
 'adama-eliya.avlah.etu/edohson-arnaud.guedou.etu' 'adame.chairi.etu/'
 'adem.kaloun.etu/' 'adem.kaloun.etu/yasser.jad.etu'
 'adnane.el-mazouni.etu/'
 'adnane.el-mazouni.etu/nils.charfeddine-barbier.etu' 'adrien.vetter.etu/'
 'ahmed.bouziani.etu/' 'ahmed.bouziani.etu/nassim.belouar.etu'
 'ahmed.terfas.etu/rayane.denni.etu' 'ahmedzeidane.mohamedelmoctar.etu/'
 'aissatou-bobo.diallo.etu/'
 'aissatou-bobo.diallo.etu/aissatou-bobo.diallo.etu'
 'aissatou-bobo.diallo.etu/fadil.sani-labo.etu'
 'alban.gahide-fournier.etu/' 'alban.gahide-fournier.etu/anas.rsmouki.etu'
 'alicia.zouadi.etu/' 'alix.carton2.etu/'
 'alix.carton2.etu/romann.szczepaniak.etu' 'alpha-abdoulaye.diallo.etu/'
 'alpha-mahmoudou.diallo.etu/'
 'alpha-mahmoudou.diallo.etu/mamadou-bachir.barry.etu'
 'alpha-mahmoudou.diallo.etu@univ-lille.fr/' 'amadou-madani.balde.etu/'
 'amadou-madani.balde.etu@univ-lille.fr/' 'amadou.balde.etu/'
 'amel.hadjloum.etu/' 'amine.khadri.etu/' 'anaba.hilary-williams.etu/'
 'anaelle.brient.etu/' 'anaelle.case.etu/' 'anais.bilek.etu/'
 'anais.bilek.etu/sadia.muhammad.etu' 'anas.bouchlaghem.etu/'
 'anas.bouchlaghem.etu/hajar.amnay.etu'
 'anas.bouchlaghem.etu/nayssam.benessalah.etu' 'anas.en-nor.etu/'
 'anas.en-nor.etu/ismail.nejjar.etu' 'anas.en-nor.etu/yasser.jad.etu'
 'anas.rsmouki.etu/' 'anass.saidi.etu/' 'anass.saidi.etu@univ-lille.fr/'
 'anass.saidi.etu@univ-lille.fr/bilel.doggui.etu' 'andy.ba.etu/'
 'andy.ba.etu/alpha-abdoulaye.diallo.etu'
 'andy.ba.etu/thierno-abdoulaye.diallo2.etu'
 'andy.ba.etu@univ-lille.fr/amine.khadri.etu' 'ania.belaida.etu/'
 'anis.bitari.etu/' 'anis.medani.etu/'
 'anis.medani.etu/ghizlane.aissaoui.etu' 'anis.younes.etu@univ-lille.fr/'
 'antoine.bollen.etu/' 'antoine.bollen.etu/avsin.ata.etu'
 'antoine.bollen.etu/julien.buseyne.etu' 'antoine.hotin.etu/'
 'antoine.hotin.etu/igor.belyaev.etu' 'antoine.lherbier.etu/'
 'antoine.vanhauwaert.etu/' 'antoine.vanhauwaert.etu/elias.debab.etu'
 'anton.dablement.etu/' 'asmaa.saibi.etu/'
 'asmaa.saibi.etu/hamza.chebbah.etu' 'assia.mousselmal.etu/'
 'assia.mousselmal.etu/clement.sorge.etu' 'augustin.derieux.etu/'
 'aurelien.bithorel.etu/' 'aurelien.bithorel.etu@univ-lille.fr/'
 'aurelien.dez.etu/' 'avsin.ata.etu/' 'avsin.ata.etu/antoine.bollen.etu'
 'avsin.ata.etu/pierrick.cardoso.etu' 'axel.flippe.etu/'
 'axel.flippe.etu/mayas.bouhadda.etu' 'aya.rhani.etu/'
 'aya.rhani.etu/safa-khawthar.draouche.etu'
 'ayao-landry-jeremie.dzossou-afanlete.etu/' 'aymeric.amblanc.etu/'
 'aymeric.amblanc.etu/hugo.vandewalle2.etu' 'ayoub.el-khayari.etu/'
 'ayoub.el-khayari.etu/youssef.airaki.etu' 'ben-magloire.hoessi.etu/'
 'bilal.oualbagui.etu/' 'bilal.ouazize.etu/' 'bilel.doggui.etu/'
 'bilel.doggui.etu/anass.saidi.etu'
 'bilel.doggui.etu/mohammed.abdennour.etu'
 'bilel.doggui.etu/nolan.halluin.etu'
 'bilel.doggui.etu@univ-lille.fr/anass.saidi.etu' 'bilel.taieb.etu/'
 'bilel.taieb.etu/julien.buseyne.etu'
 'bilel.taieb.etu/mervin.kalistas.etu' 'boris.mutagoma.etu/'
 'boris.mutagoma.etu/boris.mutagoma.etu' 'boubacar.barry.etu/'
 'candice.billerait.etu/' 'chaima.chakroun.etu/'
 'chainez.boucherim--catry.etu/' 'claire.tetart.etu/' 'clara.kombe.etu/'
 'clement.sorge.etu/' 'clement.sorge.etu/asmaa.saibi.etu'
 'clement.sorge.etu/assia.mousselmal.etu'
 'clement.sorge.etu/ibrahima.diallo8.etu' 'dania.baroud.etu/'
 'dania.baroud.etu/imrane.mehenni.etu' 'dantoire-lalle.namoni.etu/'
 'dario.bitri.etu/' 'dariya.kinadinova.etu/'
 'dariya.kinadinova.etu/imane.messali.etu' 'david.kahak.etu/'
 'demba.diao.etu/' 'demba.diao.etu/keba.thiam.etu'
 'djama.souleiman-abdi.etu/' 'douae.ramdani.etu/'
 'douae.ramdani.etu/elyna.belkacemi.etu' 'edohson-arnaud.guedou.etu/'
 'edohson-arnaud.guedou.etu/adama-eliya.avlah.etu'
 'edohson-arnaud.guedou.etu/mamadou-sellou.diallo.etu'
 'el-hadji-malick.gueye.etu/' 'elias.debab.etu/'
 'elias.debab.etu/antoine.vanhauwaert.etu' 'elliot.launay.etu/'
 'elliot.leroux.etu/' 'elyas.rabhiu.etu/' 'elyes.guedria.etu/'
 'elyes.guedria.etu/eya.yahyaoui.etu'
 'elyes.guedria.etu/walid.farrash.etu'
 'elyna.belkacemi.etu/douae.ramdani.etu' 'emeline.jonneaux-pantofel.etu/'
 'emma.souvestre.etu/' 'enrick.debailleul.etu/'
 'enrick.debailleul.etu/mehdi.rabi.etu'
 'enrick.debailleul.etu/mohamed-sami.mousaid.etu' 'enzo.dewez.etu/'
 'enzo.dewez.etu/noa.gobaut.etu' 'enzo.miuzzo.etu/'
 'enzo.miuzzo.etu/hugo.deschamps2.etu' 'ethan.duhot.etu/'
 'ethan.duhot.etu/ethan.duhot.etu' 'ethan.duhot.etu/matthieu.bouin.etu'
 'ethan.slowack.etu/' 'eya.yahyaoui.etu/'
 'eya.yahyaoui.etu/elyes.guedria.etu'
 'eya.yahyaoui.etu@univ-lille.fr/eya.yahyaoui.etu' 'eya.zeidi.etu/'
 'fadil.sani-labo.etu/' 'fadil.sani-labo.etu/aissatou-bobo.diallo.etu'
 'fadila.taffa.etu/' 'farmata-sall.sow.etu/'
 'fatima.almohamed-alsadou.etu/' 'fatoumata-bintou.traore.etu/'
 'fatoumata-bintou.traore.etu/sokhna.dia2.etu' 'faustine.descatoire.etu/'
 'fawaaz.oyedotun.etu/' 'fawaaz.oyedotun.etu/jacques-lazare.diatta.etu'
 'fayez.ben-bouali.etu/' 'fayez.ben-bouali.etu@univ-lille.fr/'
 'florian.casteur-delpierre.etu/' 'florian.heyte.etu/'
 'florian.heyte.etu/florian.heyte.etu' 'gabriel.maatouk-dorlot.etu/'
 'gabriel.maatouk-dorlot.etu/elliot.launay.etu'
 'gabriel.maatouk-dorlot.etu/jeremie.dhollande.etu'
 'ghizlane.aissaoui.etu/' 'ghizlane.aissaoui.etu/anis.medani.etu'
 'grace-rochelde.louhanana.etu/' 'guillaume.depelchin.etu/'
 'guillaume.depelchin.etu/sami.mili.etu' 'hadja-maimouna.balde.etu/'
 'hadjara.darou.etu/' 'hajar.amnay.etu/'
 'hajar.amnay.etu/anas.bouchlaghem.etu' 'hajar.zeaiter.etu/'
 'hamza.chebbah.etu/' 'hamza.chebbah.etu/nadjib.zoubir.etu'
 'hazem.hlioui.etu/' 'hazem.hlioui.etu/abderrahmen.ayadi.etu'
 'helio.dequeker.etu/' 'henry.hebelamou.etu/'
 'henry.hebelamou.etu/pedro-luis.lock-benites.etu' 'hichame.haddou.etu/'
 'hichame.haddou.etu/alicia.zouadi.etu'
 'hichame.haddou.etu/luc.duriez.etu' 'hichem.belabes.etu/'
 'hugo.deschamps2.etu/' 'hugo.deschamps2.etu/enzo.miuzzo.etu'
 'hugo.deschamps2.etu/mehdi.chaib-deraa.etu' 'hugo.leleu.etu/'
 'hugo.vandewalle2.etu/' 'hugo.vandewalle2.etu/aymeric.amblanc.etu'
 'ibn-farrid.sama.etu/' 'ibrahim.yahia.etu/'
 'ibrahim.yahia.etu/mounir.achbad.etu' 'ibrahima-al-amine.diaw.etu/'
 'ibrahima-al-amine.diaw.etu/abdoulaye.nguere.etu'
 'ibrahima-al-amine.diaw.etu/serigne.cisse.etu' 'ibrahima.diallo8.etu/'
 'ibrahima.diallo8.etu@/' 'ibrahima.diallo8.etu@univ-lille.fr/'
 'ibrahima.diop.etu/' 'ibrahima.sylla2.etu/' 'igor.belyaev.etu/'
 'ilian.briki.etu/' 'ilian.briki.etu/adam.chikh-touami.etu'
 'ilyes.benferhat.etu/' 'ilyes.benferhat.etu/louis.warembourg.etu'
 'ilyes.benferhat.etu/romain.balitout.etu' 'ilyes.hadadi.etu/'
 'ilyes.hadadi.etu/qassim.kahoul.etu' 'imad.berhoum.etu/'
 'imad.berhoum.etu/mehdi.rabi.etu' 'imane.messali.etu/'
 'imane.messali.etu/dariya.kinadinova.etu'
 'imane.messali.etu/douae.ramdani.etu'
 'imane.messali.etu/elyna.belkacemi.etu' 'imrane.mehenni.etu/'
 'imrane.mehenni.etu/asmaa.saibi.etu' 'imrane.mehenni.etu/sami.boumiz.etu'
 'imrane.mehenni.etu@univ-lille.fr/'
 'imrane.mehenni.etu@univ-lille.fr/marion.le-guen.etu'
 'ismail.nejjar.etu/' 'ismail.nejjar.etu/said.dahmani.etu'
 'ivan.mbonjo.etu/' 'jacques-lazare.diatta.etu/'
 'jacques-lazare.diatta.etu/fawaaz.oyedotun.etu' 'jean-mayes.zitouni.etu/'
 'jeremie.dhollande.etu/' 'jeremie.dhollande.etu/enzo.dewez.etu'
 'josselin.hebert.etu/' 'jules.salandre.etu/' 'julien.batrelle.etu/'
 'julien.buseyne.etu/' 'julien.buseyne.etu/antoine.bollen.etu'
 'julien.buseyne.etu/pierrick.cardoso.etu' 'julien.choquet.etu/'
 'julien.choquet.etu/anaba.hilary-williams.etu' 'julien.deneubourg.etu/'
 'julien.deneubourg.etu/florian.heyte.etu'
 'julien.deneubourg.etu/mehmet.kucukkalfa.etu' 'kade-bhoye.wann.etu/'
 'kade-bhoye.wann.etu/MI1301' 'kade-bhoye.wann.etu/MI1304'
 'kamal-deen-oloumide.savi.etu/'
 'kamal-deen-oloumide.savi.etu/dantoire-lalle.namoni.etu'
 'keba.thiam.etu/' 'kellian.sory.etu/' 'kellian.sory.etu/asmaa.saibi.etu'
 'khadim.beye.etu/' 'kilian.graye.etu/' 'kilian.graye.etu/luc'
 'kilian.graye.etu/luc.duriez.etu' 'koffi-john.evon.etu/'
 'koffi-john.evon.etu/yves.djegnon.etu' 'koffi.gantchou.etu/'
 'koffi.gantchou.etu/gora.diop.etu'
 'koffi.gantchou.etu/kotchi-ange-gedeon.kama.etu' 'komi.dogbe.etu/'
 'komivi.akpata.etu/' 'komivi.akpata.etu/dantoire-lalle.namoni.etu'
 'komivi.akpata.etu/koffi.gantchou.etu' 'kotchi-ange-gedeon.kama.etu/'
 'lansana.beavogui.etu/' 'lansana.beavogui.etu/jacques-lazare.diatta.etu'
 'lea.claire.etu/' 'lea.vannobel.etu/' 'lea.vannobel.etu/samuel.huret.etu'
 'lino.mallevaey.etu/' 'lino.mallevaey.etu/sadia.muhammad.etu'
 'lino.mallevaey.etu/yanis.brahimi.etu' 'louane.deligny.etu/'
 'louane.deligny.etu/amel.hadjloum.etu' 'loucas.meganck.etu/'
 'louis.warembourg.etu/' 'louis.warembourg.etu/thomas.desbuissons.etu'
 'luc.duriez.etu/' 'luc.duriez.etu/kilian.graye.etu' 'lucile.viau.etu/'
 'lucile.viau.etu/thibault.maton.etu' 'lyna.boussahela.etu/'
 'm-bah-ange-pascal.tanoh.etu/'
 'm-bah-ange-pascal.tanoh.etu/manel.kracheni.etu'
 'm-bah-ange-pascal.tanoh.etu@univ-lille.fr/'
 'maeva.coppey.etu/hajar.amnay.etu'
 'maeva.coppey.etu/nayssam.benessalah.etu' 'maeva.ochsenfeld.etu/'
 'magatte.mbathie.etu/' 'malak.boudoh-mimun.etu/'
 'malak.boudoh-mimun.etu/shirel.da-silva.etu' 'malick-ndiaye.kone.etu/'
 'mamadou-alpha.diallo2.etu/' 'mamadou-bachir.barry.etu/'
 'mamadou-sellou.diallo.etu/'
 'mamadou-sellou.diallo.etu/mervin.kalistas.etu' 'mamadou.barry8.etu/'
 'mamadou.diallo9.etu/' 'mamadou.diallo9.etu/mamadou.diallo9.etu'
 'mamadou.manga.etu/' 'mame-diarra.tall.etu/' 'mame-ngor.aw.etu/'
 'manel.cherief.etu/' 'manel.cherief.etu/hajar.amnay.etu'
 'manel.cherief.etu/serigne.cisse.etu' 'manel.kracheni.etu/'
 'manel.kracheni.etu/douae.ramdani.etu'
 'manel.kracheni.etu/fawaaz.oyedotun.etu'
 'manel.kracheni.etu/m-bah-ange-pascal.tanoh.etu' 'maodo.niang.etu/'
 'marcio.vieira-matos.etu/' 'marion.le-guen.etu/'
 'marion.le-guen.etu/imrane.mehenni.etu'
 'marion.le-guen.etu/walid.farrash.etu'
 'marion.le-guen.etu@univ-lille.fr/' 'marko.yanovskyi.etu/'
 'maryam.hezzat.etu/' 'massama.keita.etu/' 'massil.kichi.etu/'
 'matheo.facon.etu/' 'matheo.paszkowski.etu/' 'mathis.thomas.etu/'
 'mathis.thomas.etu/paul.heroguel.etu' 'matthieu.bouin.etu/'
 'matthieu.misiak.etu/' 'matthieu.misiak.etu/loucas.meganck.etu'
 'maxence.magras.etu/' 'maxime.mpungwe.etu/'
 'maxime.mpungwe.etu/ahmed.terfas.etu' 'mayas.bouhadda.etu/'
 'mehdi.chaib-deraa.etu/' 'mehdi.rabi.etu/'
 'mehdi.rabi.etu/imad.berhoum.etu' 'mehdi.rabi.etu/mehdi.rabi.etu'
 'mehmet.kucukkalfa.etu/' 'mervin.kalistas.etu/'
 'mervin.kalistas.etu/mamadou-sellou.diallo.etu' 'merwan.sergent.etu/'
 'michael.tankeu-bigna.etu/' 'milan.caillot.etu/'
 'mirdaas-alfa-kaza.alidou.etu/' 'mohamed-el-amine.samahri.etu/'
 'mohamed-el-amine.samahri.etu@univ-lille.fr/'
 'mohamed-nazim.ait-kaci.etu/' 'mohamed-sami.mousaid.etu/'
 'mohamed-sami.mousaid.etu/enrick.debailleul.etu' 'mohamed.belfadel.etu/'
 'mohamed.belfadel.etu/rayane.asma.etu' 'mohamed.djafer.etu/'
 'mohamed.mana.etu/' 'mohamed.mana.etu/naim.abdellaoui.etu'
 'mohamed.mana.etu/samuel.scavone.etu' 'mohamed.mana.etu/tarik.amirat.etu'
 'mohamed.trougouty.etu/' 'mohamed.zemmouri.etu/'
 'mohammed.abdennour.etu/' 'mohammed.abdennour.etu/bilel.doggui.etu'
 'momar.niang.etu/' 'momar.niang.etu/mamadou.manga.etu'
 'mounir.achbad.etu/' 'mounir.achbad.etu/ibrahim.yahia.etu'
 'mounir.zebboudji.etu/' 'mugisha.nzakamwita.etu/'
 'mugisha.nzakamwita.etu/alpha-abdoulaye.diallo.etu'
 'mugisha.nzakamwita.etu@univ-lille.fr/' 'nadjib.zoubir.etu/'
 'naim.abdellaoui.etu/' 'naim.abdellaoui.etu/mohamed.mana.etu'
 'nassim.abbad.etu/' 'nassim.abbad.etu/nassim.abbad.etu'
 'nassim.arbaoui.etu/' 'nassim.arbaoui.etu/willy.nguyen.etu'
 'nassim.belouar.etu/' 'nassim.belouar.etu/ahmed.bouziani.etu'
 'nassim.belouar.etu/alicia.zouadi.etu'
 'nassim.belouar.etu@univ-lille.fr/' 'nathan.remoleux.etu/'
 'nayad.senaici.etu/' 'nayssam.benessalah.etu/'
 'nayssam.benessalah.etu/anas.bouchlaghem.etu' 'ndongo.diao.etu/' 'nebut/'
 'nhungocanh.nguyen.etu/' 'nicolas.raharinaivo.etu/'
 'nicolas.raharinaivo.etu/noa.gobaut.etu' 'nils.charfeddine-barbier.etu/'
 'nils.charfeddine-barbier.etu/florian.casteur-delpierre.etu'
 'noa.gobaut.etu/' 'noa.gobaut.etu@univ-lille.fr/' 'noam.taibi.etu/'
 'noam.taibi.etu/yanko.lemoine.etu' 'noe.carpentier.etu/'
 'noe.le-van-canh-dit-ban.etu/' 'nolan.chevalier.etu/'
 'nolan.halluin.etu/' 'nolan.halluin.etu/abdallah.saint-ghislain.etu'
 'nourou.diouf.etu/' 'oscar.abidi.etu/' 'oumou.diallo3.etu/'
 'oyawa.liza.etu/' 'pap-amath.thiam.etu/' 'paul.heroguel.etu/'
 'paul.heroguel.etu/josselin.hebert.etu' 'pedro-luis.lock-benites.etu/'
 'pedro-luis.lock-benites.etu/henry.hebelamou.etu'
 'pedro-luis.lock-benites.etu/shema.mugambira.etu' 'pierre.delecourt.etu/'
 'pierrick.cardoso.etu/' 'pierrick.cardoso.etu/avsin.ata.etu'
 'qassim.kahoul.etu/' 'qassim.kahoul.etu/ilyes.hadadi.etu'
 'qassim.kahoul.etu/mehdi.rabi.etu' 'raphael.crozat-moreau.etu/'
 'raphael.tafani.etu/' 'rayan.fortas.etu/' 'rayane.asma.etu/'
 'rayane.denni.etu/' 'rayane.denni.etu/adame.chairi.etu'
 'rayane.denni.etu/ahmed.terfas.etu' 'richard.kpande-adzare.etu/'
 'richard.kpande-adzare.etu/oumou.diallo3.etu' 'romain.balitout.etu/'
 'romain.balitout.etu/ilyes.benferhat.etu' 'romain.faidherbe.etu/'
 'romain.faidherbe.etu/salim.rachdi.etu' 'romain.ruelle.etu/'
 'romane.deleau.etu/' 'romane.deleau.etu/imrane.mehenni.etu'
 'romane.deleau.etu/marion.le-guen.etu'
 'romane.deleau.etu/sami.boumiz.etu' 'romann.szczepaniak.etu/'
 'romann.szczepaniak.etu/alix.carton2.etu'
 'rosche-rostell.batchi-vouala.etu/' 'rose.pananceau.etu/'
 'rose.pananceau.etu/pap-amath.thiam.etu' 'ruben.cassin.etu/'
 'sabine.boukais.etu/' 'sadia.muhammad.etu/' 'safa-khawthar.draouche.etu/'
 'safa-khawthar.draouche.etu/aya.rhani.etu' 'said.dahmani.etu/'
 'said.dahmani.etu/ismail.nejjar.etu' 'said.dahmani.etu/said.dahmani.etu'
 'salem.el-bouhouti.etu/'
 'salem.el-bouhouti.etu/mohamed-el-amine.samahri.etu' 'salim.rachdi.etu/'
 'sami.boumiz.etu/' 'sami.boumiz.etu/hamza.chebbah.etu' 'sami.mili.etu/'
 'sami.mili.etu/sami.mili.etu' 'samir.fandi.etu/'
 'samir.fandi.etu@univ-lille.fr/' 'samuel.huret.etu/'
 'samuel.huret.etu/faustine.descatoire.etu'
 'samuel.huret.etu/lea.vannobel.etu' 'samuel.scavone.etu/'
 'samuel.scavone.etu/hichame.haddou.etu'
 'samuel.scavone.etu/yastene.chemam.etu' 'samy.yahia-cherif.etu/'
 'samy.yahia-cherif.etu/samy.yahia-cherif.etu'
 'samy.yahia-cherif.etu/yanis.nabet.etu' 'serhii.ivkin.etu/'
 'serigne.cisse.etu/' 'serigne.cisse.etu/abdoulaye.nguere.etu'
 'serigne.cisse.etu/manel.cherief.etu'
 'serigne.cisse.etu/rayane.denni.etu' 'shadrak-arthur.banouanina.etu/'
 'shadrak-arthur.banouanina.etu/komivi.akpata.etu' 'shema.mugambira.etu/'
 'shirel.da-silva.etu/' 'shirel.da-silva.etu/malak.boudoh-mimun.etu'
 'shirel.da-silva.etu/maodo.niang.etu' 'sokhna.dia2.etu/'
 'sokhna.dia2.etu/fatoumata-bintou.traore.etu'
 'sokhna.dia2.etu/hadjara.darou.etu' 'taissir.el-hammouchi.etu/'
 'tarik.amirat.etu/' 'thibault.maton.etu/'
 'thibault.maton.etu/lucile.viau.etu' 'thierno-abdoulaye.diallo2.etu/'
 'thierno-abdoulaye.diallo2.etu/andy.ba.etu' 'thierno.barry4.etu/'
 'thomas.desbuissons.etu/' 'thomas.desbuissons.etu/ahmed.bouziani.etu'
 'thomas.desbuissons.etu/louis.warembourg.etu' 'timothe.devigne.etu/'
 'tristan.melchior.etu/' 'valentin.faust.etu/' 'wail.ghouila.etu/'
 'walid.farrash.etu/' 'walid.farrash.etu/asmaa.saibi.etu'
 'walid.farrash.etu/elyes.guedria.etu'
 'walid.farrash.etu/eya.yahyaoui.etu' 'waylan.godfrey.etu/'
 'weeti-sharleen.akogbeto.etu/' 'willy.nguyen.etu/'
 'willy.nguyen.etu/nassim.arbaoui.etu' 'yadiradjen.mounien.etu/'
 'yanis.brahimi.etu/' 'yanis.gannar.etu/'
 'yanis.gannar.etu/david.kahak.etu' 'yanis.kharchi.etu/'
 'yanis.nabet.etu/' 'yanis.nabet.etu/samy.yahia-cherif.etu'
 'yanko.lemoine.etu/' 'yanko.lemoine.etu/noam.taibi.etu' 'yasser.jad.etu/'
 'yastene.chemam.etu/' 'yastene.chemam.etu/alicia.zouadi.etu'
 'yastene.chemam.etu/naim.abdellaoui.etu'
 'yastene.chemam.etu/samuel.scavone.etu'
 'yastene.chemam.etu/tarik.amirat.etu'
 'yastene.chemam.etu/yastene.chemam.etu' 'yohan.michel.etu/'
 'youssef.airaki.etu/' 'yves.djegnon.etu/'
 'yves.djegnon.etu/fatoumata-bintou.traore.etu' 'zacharie.deroo.etu/'
 'zacharie.deroo.etu/noe.carpentier.etu']

In [9]:
# Apply deleting
df = data_cleaning.delete_end_email(df)
df['actor'].unique() # After deleting

array(['abaly.oura.etu/', 'abaly.oura.etu',
       'abdallah.saint-ghislain.etu/', 'abdelrahmane.bendjeladjel.etu/',
       'abderrahmen.ayadi.etu/',
       'abderrahmen.ayadi.etu/abderrahmen.ayadi.etu',
       'abderrahmen.ayadi.etu/hazem.hlioui.etu', 'abdoulaye.mbaye.etu/',
       'abdoulaye.nguere.etu/', 'abdoulaye.nguere.etu/serigne.cisse.etu',
       'adam.chikh-touami.etu/', 'adam.chikh-touami.etu/ilian.briki.etu',
       'adam.oukzedou.etu/', 'adam.sialiti.etu/',
       'adama-eliya.avlah.etu/',
       'adama-eliya.avlah.etu/edohson-arnaud.guedou.etu',
       'adame.chairi.etu/', 'adem.kaloun.etu/',
       'adem.kaloun.etu/yasser.jad.etu', 'adnane.el-mazouni.etu/',
       'adnane.el-mazouni.etu/nils.charfeddine-barbier.etu',
       'adrien.vetter.etu/', 'ahmed.bouziani.etu/',
       'ahmed.bouziani.etu/nassim.belouar.etu',
       'ahmed.terfas.etu/rayane.denni.etu',
       'ahmedzeidane.mohamedelmoctar.etu/', 'aissatou-bobo.diallo.etu/',
       'aissatou-bobo.diallo.etu/aissatou-bobo.diallo.etu',
       'aissatou-bobo.diallo.etu/fadil.sani-labo.etu',
       'alban.gahide-fournier.etu/',
       'alban.gahide-fournier.etu/anas.rsmouki.etu', 'alicia.zouadi.etu/',
       'alix.carton2.etu/', 'alix.carton2.etu/romann.szczepaniak.etu',
       'alpha-abdoulaye.diallo.etu/', 'alpha-mahmoudou.diallo.etu/',
       'alpha-mahmoudou.diallo.etu/mamadou-bachir.barry.etu',
       'alpha-mahmoudou.diallo.etu', 'amadou-madani.balde.etu/',
       'amadou-madani.balde.etu', 'amadou.balde.etu/',
       'amel.hadjloum.etu/', 'amine.khadri.etu/',
       'anaba.hilary-williams.etu/', 'anaelle.brient.etu/',
       'anaelle.case.etu/', 'anais.bilek.etu/',
       'anais.bilek.etu/sadia.muhammad.etu', 'anas.bouchlaghem.etu/',
       'anas.bouchlaghem.etu/hajar.amnay.etu',
       'anas.bouchlaghem.etu/nayssam.benessalah.etu', 'anas.en-nor.etu/',
       'anas.en-nor.etu/ismail.nejjar.etu',
       'anas.en-nor.etu/yasser.jad.etu', 'anas.rsmouki.etu/',
       'anass.saidi.etu/', 'anass.saidi.etu', 'andy.ba.etu/',
       'andy.ba.etu/alpha-abdoulaye.diallo.etu',
       'andy.ba.etu/thierno-abdoulaye.diallo2.etu', 'andy.ba.etu',
       'ania.belaida.etu/', 'anis.bitari.etu/', 'anis.medani.etu/',
       'anis.medani.etu/ghizlane.aissaoui.etu', 'anis.younes.etu',
       'antoine.bollen.etu/', 'antoine.bollen.etu/avsin.ata.etu',
       'antoine.bollen.etu/julien.buseyne.etu', 'antoine.hotin.etu/',
       'antoine.hotin.etu/igor.belyaev.etu', 'antoine.lherbier.etu/',
       'antoine.vanhauwaert.etu/',
       'antoine.vanhauwaert.etu/elias.debab.etu', 'anton.dablement.etu/',
       'asmaa.saibi.etu/', 'asmaa.saibi.etu/hamza.chebbah.etu',
       'assia.mousselmal.etu/', 'assia.mousselmal.etu/clement.sorge.etu',
       'augustin.derieux.etu/', 'aurelien.bithorel.etu/',
       'aurelien.bithorel.etu', 'aurelien.dez.etu/', 'avsin.ata.etu/',
       'avsin.ata.etu/antoine.bollen.etu',
       'avsin.ata.etu/pierrick.cardoso.etu', 'axel.flippe.etu/',
       'axel.flippe.etu/mayas.bouhadda.etu', 'aya.rhani.etu/',
       'aya.rhani.etu/safa-khawthar.draouche.etu',
       'ayao-landry-jeremie.dzossou-afanlete.etu/',
       'aymeric.amblanc.etu/', 'aymeric.amblanc.etu/hugo.vandewalle2.etu',
       'ayoub.el-khayari.etu/', 'ayoub.el-khayari.etu/youssef.airaki.etu',
       'ben-magloire.hoessi.etu/', 'bilal.oualbagui.etu/',
       'bilal.ouazize.etu/', 'bilel.doggui.etu/',
       'bilel.doggui.etu/anass.saidi.etu',
       'bilel.doggui.etu/mohammed.abdennour.etu',
       'bilel.doggui.etu/nolan.halluin.etu', 'bilel.doggui.etu',
       'bilel.taieb.etu/', 'bilel.taieb.etu/julien.buseyne.etu',
       'bilel.taieb.etu/mervin.kalistas.etu', 'boris.mutagoma.etu/',
       'boris.mutagoma.etu/boris.mutagoma.etu', 'boubacar.barry.etu/',
       'candice.billerait.etu/', 'chaima.chakroun.etu/',
       'chainez.boucherim--catry.etu/', 'claire.tetart.etu/',
       'clara.kombe.etu/', 'clement.sorge.etu/',
       'clement.sorge.etu/asmaa.saibi.etu',
       'clement.sorge.etu/assia.mousselmal.etu',
       'clement.sorge.etu/ibrahima.diallo8.etu', 'dania.baroud.etu/',
       'dania.baroud.etu/imrane.mehenni.etu',
       'dantoire-lalle.namoni.etu/', 'dario.bitri.etu/',
       'dariya.kinadinova.etu/',
       'dariya.kinadinova.etu/imane.messali.etu', 'david.kahak.etu/',
       'demba.diao.etu/', 'demba.diao.etu/keba.thiam.etu',
       'djama.souleiman-abdi.etu/', 'douae.ramdani.etu/',
       'douae.ramdani.etu/elyna.belkacemi.etu',
       'edohson-arnaud.guedou.etu/',
       'edohson-arnaud.guedou.etu/adama-eliya.avlah.etu',
       'edohson-arnaud.guedou.etu/mamadou-sellou.diallo.etu',
       'el-hadji-malick.gueye.etu/', 'elias.debab.etu/',
       'elias.debab.etu/antoine.vanhauwaert.etu', 'elliot.launay.etu/',
       'elliot.leroux.etu/', 'elyas.rabhiu.etu/', 'elyes.guedria.etu/',
       'elyes.guedria.etu/eya.yahyaoui.etu',
       'elyes.guedria.etu/walid.farrash.etu',
       'elyna.belkacemi.etu/douae.ramdani.etu',
       'emeline.jonneaux-pantofel.etu/', 'emma.souvestre.etu/',
       'enrick.debailleul.etu/', 'enrick.debailleul.etu/mehdi.rabi.etu',
       'enrick.debailleul.etu/mohamed-sami.mousaid.etu',
       'enzo.dewez.etu/', 'enzo.dewez.etu/noa.gobaut.etu',
       'enzo.miuzzo.etu/', 'enzo.miuzzo.etu/hugo.deschamps2.etu',
       'ethan.duhot.etu/', 'ethan.duhot.etu/ethan.duhot.etu',
       'ethan.duhot.etu/matthieu.bouin.etu', 'ethan.slowack.etu/',
       'eya.yahyaoui.etu/', 'eya.yahyaoui.etu/elyes.guedria.etu',
       'eya.yahyaoui.etu', 'eya.zeidi.etu/', 'fadil.sani-labo.etu/',
       'fadil.sani-labo.etu/aissatou-bobo.diallo.etu',
       'fadila.taffa.etu/', 'farmata-sall.sow.etu/',
       'fatima.almohamed-alsadou.etu/', 'fatoumata-bintou.traore.etu/',
       'fatoumata-bintou.traore.etu/sokhna.dia2.etu',
       'faustine.descatoire.etu/', 'fawaaz.oyedotun.etu/',
       'fawaaz.oyedotun.etu/jacques-lazare.diatta.etu',
       'fayez.ben-bouali.etu/', 'fayez.ben-bouali.etu',
       'florian.casteur-delpierre.etu/', 'florian.heyte.etu/',
       'florian.heyte.etu/florian.heyte.etu',
       'gabriel.maatouk-dorlot.etu/',
       'gabriel.maatouk-dorlot.etu/elliot.launay.etu',
       'gabriel.maatouk-dorlot.etu/jeremie.dhollande.etu',
       'ghizlane.aissaoui.etu/', 'ghizlane.aissaoui.etu/anis.medani.etu',
       'grace-rochelde.louhanana.etu/', 'guillaume.depelchin.etu/',
       'guillaume.depelchin.etu/sami.mili.etu',
       'hadja-maimouna.balde.etu/', 'hadjara.darou.etu/',
       'hajar.amnay.etu/', 'hajar.amnay.etu/anas.bouchlaghem.etu',
       'hajar.zeaiter.etu/', 'hamza.chebbah.etu/',
       'hamza.chebbah.etu/nadjib.zoubir.etu', 'hazem.hlioui.etu/',
       'hazem.hlioui.etu/abderrahmen.ayadi.etu', 'helio.dequeker.etu/',
       'henry.hebelamou.etu/',
       'henry.hebelamou.etu/pedro-luis.lock-benites.etu',
       'hichame.haddou.etu/', 'hichame.haddou.etu/alicia.zouadi.etu',
       'hichame.haddou.etu/luc.duriez.etu', 'hichem.belabes.etu/',
       'hugo.deschamps2.etu/', 'hugo.deschamps2.etu/enzo.miuzzo.etu',
       'hugo.deschamps2.etu/mehdi.chaib-deraa.etu', 'hugo.leleu.etu/',
       'hugo.vandewalle2.etu/',
       'hugo.vandewalle2.etu/aymeric.amblanc.etu', 'ibn-farrid.sama.etu/',
       'ibrahim.yahia.etu/', 'ibrahim.yahia.etu/mounir.achbad.etu',
       'ibrahima-al-amine.diaw.etu/',
       'ibrahima-al-amine.diaw.etu/abdoulaye.nguere.etu',
       'ibrahima-al-amine.diaw.etu/serigne.cisse.etu',
       'ibrahima.diallo8.etu/', 'ibrahima.diallo8.etu',
       'ibrahima.diop.etu/', 'ibrahima.sylla2.etu/', 'igor.belyaev.etu/',
       'ilian.briki.etu/', 'ilian.briki.etu/adam.chikh-touami.etu',
       'ilyes.benferhat.etu/', 'ilyes.benferhat.etu/louis.warembourg.etu',
       'ilyes.benferhat.etu/romain.balitout.etu', 'ilyes.hadadi.etu/',
       'ilyes.hadadi.etu/qassim.kahoul.etu', 'imad.berhoum.etu/',
       'imad.berhoum.etu/mehdi.rabi.etu', 'imane.messali.etu/',
       'imane.messali.etu/dariya.kinadinova.etu',
       'imane.messali.etu/douae.ramdani.etu',
       'imane.messali.etu/elyna.belkacemi.etu', 'imrane.mehenni.etu/',
       'imrane.mehenni.etu/asmaa.saibi.etu',
       'imrane.mehenni.etu/sami.boumiz.etu', 'imrane.mehenni.etu',
       'ismail.nejjar.etu/', 'ismail.nejjar.etu/said.dahmani.etu',
       'ivan.mbonjo.etu/', 'jacques-lazare.diatta.etu/',
       'jacques-lazare.diatta.etu/fawaaz.oyedotun.etu',
       'jean-mayes.zitouni.etu/', 'jeremie.dhollande.etu/',
       'jeremie.dhollande.etu/enzo.dewez.etu', 'josselin.hebert.etu/',
       'jules.salandre.etu/', 'julien.batrelle.etu/',
       'julien.buseyne.etu/', 'julien.buseyne.etu/antoine.bollen.etu',
       'julien.buseyne.etu/pierrick.cardoso.etu', 'julien.choquet.etu/',
       'julien.choquet.etu/anaba.hilary-williams.etu',
       'julien.deneubourg.etu/',
       'julien.deneubourg.etu/florian.heyte.etu',
       'julien.deneubourg.etu/mehmet.kucukkalfa.etu',
       'kade-bhoye.wann.etu/', 'kade-bhoye.wann.etu/MI1301',
       'kade-bhoye.wann.etu/MI1304', 'kamal-deen-oloumide.savi.etu/',
       'kamal-deen-oloumide.savi.etu/dantoire-lalle.namoni.etu',
       'keba.thiam.etu/', 'kellian.sory.etu/',
       'kellian.sory.etu/asmaa.saibi.etu', 'khadim.beye.etu/',
       'kilian.graye.etu/', 'kilian.graye.etu/luc',
       'kilian.graye.etu/luc.duriez.etu', 'koffi-john.evon.etu/',
       'koffi-john.evon.etu/yves.djegnon.etu', 'koffi.gantchou.etu/',
       'koffi.gantchou.etu/gora.diop.etu',
       'koffi.gantchou.etu/kotchi-ange-gedeon.kama.etu',
       'komi.dogbe.etu/', 'komivi.akpata.etu/',
       'komivi.akpata.etu/dantoire-lalle.namoni.etu',
       'komivi.akpata.etu/koffi.gantchou.etu',
       'kotchi-ange-gedeon.kama.etu/', 'lansana.beavogui.etu/',
       'lansana.beavogui.etu/jacques-lazare.diatta.etu',
       'lea.claire.etu/', 'lea.vannobel.etu/',
       'lea.vannobel.etu/samuel.huret.etu', 'lino.mallevaey.etu/',
       'lino.mallevaey.etu/sadia.muhammad.etu',
       'lino.mallevaey.etu/yanis.brahimi.etu', 'louane.deligny.etu/',
       'louane.deligny.etu/amel.hadjloum.etu', 'loucas.meganck.etu/',
       'louis.warembourg.etu/',
       'louis.warembourg.etu/thomas.desbuissons.etu', 'luc.duriez.etu/',
       'luc.duriez.etu/kilian.graye.etu', 'lucile.viau.etu/',
       'lucile.viau.etu/thibault.maton.etu', 'lyna.boussahela.etu/',
       'm-bah-ange-pascal.tanoh.etu/',
       'm-bah-ange-pascal.tanoh.etu/manel.kracheni.etu',
       'm-bah-ange-pascal.tanoh.etu', 'maeva.coppey.etu/hajar.amnay.etu',
       'maeva.coppey.etu/nayssam.benessalah.etu', 'maeva.ochsenfeld.etu/',
       'magatte.mbathie.etu/', 'malak.boudoh-mimun.etu/',
       'malak.boudoh-mimun.etu/shirel.da-silva.etu',
       'malick-ndiaye.kone.etu/', 'mamadou-alpha.diallo2.etu/',
       'mamadou-bachir.barry.etu/', 'mamadou-sellou.diallo.etu/',
       'mamadou-sellou.diallo.etu/mervin.kalistas.etu',
       'mamadou.barry8.etu/', 'mamadou.diallo9.etu/',
       'mamadou.diallo9.etu/mamadou.diallo9.etu', 'mamadou.manga.etu/',
       'mame-diarra.tall.etu/', 'mame-ngor.aw.etu/', 'manel.cherief.etu/',
       'manel.cherief.etu/hajar.amnay.etu',
       'manel.cherief.etu/serigne.cisse.etu', 'manel.kracheni.etu/',
       'manel.kracheni.etu/douae.ramdani.etu',
       'manel.kracheni.etu/fawaaz.oyedotun.etu',
       'manel.kracheni.etu/m-bah-ange-pascal.tanoh.etu',
       'maodo.niang.etu/', 'marcio.vieira-matos.etu/',
       'marion.le-guen.etu/', 'marion.le-guen.etu/imrane.mehenni.etu',
       'marion.le-guen.etu/walid.farrash.etu', 'marion.le-guen.etu',
       'marko.yanovskyi.etu/', 'maryam.hezzat.etu/', 'massama.keita.etu/',
       'massil.kichi.etu/', 'matheo.facon.etu/', 'matheo.paszkowski.etu/',
       'mathis.thomas.etu/', 'mathis.thomas.etu/paul.heroguel.etu',
       'matthieu.bouin.etu/', 'matthieu.misiak.etu/',
       'matthieu.misiak.etu/loucas.meganck.etu', 'maxence.magras.etu/',
       'maxime.mpungwe.etu/', 'maxime.mpungwe.etu/ahmed.terfas.etu',
       'mayas.bouhadda.etu/', 'mehdi.chaib-deraa.etu/', 'mehdi.rabi.etu/',
       'mehdi.rabi.etu/imad.berhoum.etu', 'mehdi.rabi.etu/mehdi.rabi.etu',
       'mehmet.kucukkalfa.etu/', 'mervin.kalistas.etu/',
       'mervin.kalistas.etu/mamadou-sellou.diallo.etu',
       'merwan.sergent.etu/', 'michael.tankeu-bigna.etu/',
       'milan.caillot.etu/', 'mirdaas-alfa-kaza.alidou.etu/',
       'mohamed-el-amine.samahri.etu/', 'mohamed-el-amine.samahri.etu',
       'mohamed-nazim.ait-kaci.etu/', 'mohamed-sami.mousaid.etu/',
       'mohamed-sami.mousaid.etu/enrick.debailleul.etu',
       'mohamed.belfadel.etu/', 'mohamed.belfadel.etu/rayane.asma.etu',
       'mohamed.djafer.etu/', 'mohamed.mana.etu/',
       'mohamed.mana.etu/naim.abdellaoui.etu',
       'mohamed.mana.etu/samuel.scavone.etu',
       'mohamed.mana.etu/tarik.amirat.etu', 'mohamed.trougouty.etu/',
       'mohamed.zemmouri.etu/', 'mohammed.abdennour.etu/',
       'mohammed.abdennour.etu/bilel.doggui.etu', 'momar.niang.etu/',
       'momar.niang.etu/mamadou.manga.etu', 'mounir.achbad.etu/',
       'mounir.achbad.etu/ibrahim.yahia.etu', 'mounir.zebboudji.etu/',
       'mugisha.nzakamwita.etu/',
       'mugisha.nzakamwita.etu/alpha-abdoulaye.diallo.etu',
       'mugisha.nzakamwita.etu', 'nadjib.zoubir.etu/',
       'naim.abdellaoui.etu/', 'naim.abdellaoui.etu/mohamed.mana.etu',
       'nassim.abbad.etu/', 'nassim.abbad.etu/nassim.abbad.etu',
       'nassim.arbaoui.etu/', 'nassim.arbaoui.etu/willy.nguyen.etu',
       'nassim.belouar.etu/', 'nassim.belouar.etu/ahmed.bouziani.etu',
       'nassim.belouar.etu/alicia.zouadi.etu', 'nassim.belouar.etu',
       'nathan.remoleux.etu/', 'nayad.senaici.etu/',
       'nayssam.benessalah.etu/',
       'nayssam.benessalah.etu/anas.bouchlaghem.etu', 'ndongo.diao.etu/',
       'nebut/', 'nhungocanh.nguyen.etu/', 'nicolas.raharinaivo.etu/',
       'nicolas.raharinaivo.etu/noa.gobaut.etu',
       'nils.charfeddine-barbier.etu/',
       'nils.charfeddine-barbier.etu/florian.casteur-delpierre.etu',
       'noa.gobaut.etu/', 'noa.gobaut.etu', 'noam.taibi.etu/',
       'noam.taibi.etu/yanko.lemoine.etu', 'noe.carpentier.etu/',
       'noe.le-van-canh-dit-ban.etu/', 'nolan.chevalier.etu/',
       'nolan.halluin.etu/',
       'nolan.halluin.etu/abdallah.saint-ghislain.etu',
       'nourou.diouf.etu/', 'oscar.abidi.etu/', 'oumou.diallo3.etu/',
       'oyawa.liza.etu/', 'pap-amath.thiam.etu/', 'paul.heroguel.etu/',
       'paul.heroguel.etu/josselin.hebert.etu',
       'pedro-luis.lock-benites.etu/',
       'pedro-luis.lock-benites.etu/henry.hebelamou.etu',
       'pedro-luis.lock-benites.etu/shema.mugambira.etu',
       'pierre.delecourt.etu/', 'pierrick.cardoso.etu/',
       'pierrick.cardoso.etu/avsin.ata.etu', 'qassim.kahoul.etu/',
       'qassim.kahoul.etu/ilyes.hadadi.etu',
       'qassim.kahoul.etu/mehdi.rabi.etu', 'raphael.crozat-moreau.etu/',
       'raphael.tafani.etu/', 'rayan.fortas.etu/', 'rayane.asma.etu/',
       'rayane.denni.etu/', 'rayane.denni.etu/adame.chairi.etu',
       'rayane.denni.etu/ahmed.terfas.etu', 'richard.kpande-adzare.etu/',
       'richard.kpande-adzare.etu/oumou.diallo3.etu',
       'romain.balitout.etu/', 'romain.balitout.etu/ilyes.benferhat.etu',
       'romain.faidherbe.etu/', 'romain.faidherbe.etu/salim.rachdi.etu',
       'romain.ruelle.etu/', 'romane.deleau.etu/',
       'romane.deleau.etu/imrane.mehenni.etu',
       'romane.deleau.etu/marion.le-guen.etu',
       'romane.deleau.etu/sami.boumiz.etu', 'romann.szczepaniak.etu/',
       'romann.szczepaniak.etu/alix.carton2.etu',
       'rosche-rostell.batchi-vouala.etu/', 'rose.pananceau.etu/',
       'rose.pananceau.etu/pap-amath.thiam.etu', 'ruben.cassin.etu/',
       'sabine.boukais.etu/', 'sadia.muhammad.etu/',
       'safa-khawthar.draouche.etu/',
       'safa-khawthar.draouche.etu/aya.rhani.etu', 'said.dahmani.etu/',
       'said.dahmani.etu/ismail.nejjar.etu',
       'said.dahmani.etu/said.dahmani.etu', 'salem.el-bouhouti.etu/',
       'salem.el-bouhouti.etu/mohamed-el-amine.samahri.etu',
       'salim.rachdi.etu/', 'sami.boumiz.etu/',
       'sami.boumiz.etu/hamza.chebbah.etu', 'sami.mili.etu/',
       'sami.mili.etu/sami.mili.etu', 'samir.fandi.etu/',
       'samir.fandi.etu', 'samuel.huret.etu/',
       'samuel.huret.etu/faustine.descatoire.etu',
       'samuel.huret.etu/lea.vannobel.etu', 'samuel.scavone.etu/',
       'samuel.scavone.etu/hichame.haddou.etu',
       'samuel.scavone.etu/yastene.chemam.etu', 'samy.yahia-cherif.etu/',
       'samy.yahia-cherif.etu/samy.yahia-cherif.etu',
       'samy.yahia-cherif.etu/yanis.nabet.etu', 'serhii.ivkin.etu/',
       'serigne.cisse.etu/', 'serigne.cisse.etu/abdoulaye.nguere.etu',
       'serigne.cisse.etu/manel.cherief.etu',
       'serigne.cisse.etu/rayane.denni.etu',
       'shadrak-arthur.banouanina.etu/',
       'shadrak-arthur.banouanina.etu/komivi.akpata.etu',
       'shema.mugambira.etu/', 'shirel.da-silva.etu/',
       'shirel.da-silva.etu/malak.boudoh-mimun.etu',
       'shirel.da-silva.etu/maodo.niang.etu', 'sokhna.dia2.etu/',
       'sokhna.dia2.etu/fatoumata-bintou.traore.etu',
       'sokhna.dia2.etu/hadjara.darou.etu', 'taissir.el-hammouchi.etu/',
       'tarik.amirat.etu/', 'thibault.maton.etu/',
       'thibault.maton.etu/lucile.viau.etu',
       'thierno-abdoulaye.diallo2.etu/',
       'thierno-abdoulaye.diallo2.etu/andy.ba.etu', 'thierno.barry4.etu/',
       'thomas.desbuissons.etu/',
       'thomas.desbuissons.etu/ahmed.bouziani.etu',
       'thomas.desbuissons.etu/louis.warembourg.etu',
       'timothe.devigne.etu/', 'tristan.melchior.etu/',
       'valentin.faust.etu/', 'wail.ghouila.etu/', 'walid.farrash.etu/',
       'walid.farrash.etu/asmaa.saibi.etu',
       'walid.farrash.etu/elyes.guedria.etu',
       'walid.farrash.etu/eya.yahyaoui.etu', 'waylan.godfrey.etu/',
       'weeti-sharleen.akogbeto.etu/', 'willy.nguyen.etu/',
       'willy.nguyen.etu/nassim.arbaoui.etu', 'yadiradjen.mounien.etu/',
       'yanis.brahimi.etu/', 'yanis.gannar.etu/',
       'yanis.gannar.etu/david.kahak.etu', 'yanis.kharchi.etu/',
       'yanis.nabet.etu/', 'yanis.nabet.etu/samy.yahia-cherif.etu',
       'yanko.lemoine.etu/', 'yanko.lemoine.etu/noam.taibi.etu',
       'yasser.jad.etu/', 'yastene.chemam.etu/',
       'yastene.chemam.etu/alicia.zouadi.etu',
       'yastene.chemam.etu/naim.abdellaoui.etu',
       'yastene.chemam.etu/samuel.scavone.etu',
       'yastene.chemam.etu/tarik.amirat.etu',
       'yastene.chemam.etu/yastene.chemam.etu', 'yohan.michel.etu/',
       'youssef.airaki.etu/', 'yves.djegnon.etu/',
       'yves.djegnon.etu/fatoumata-bintou.traore.etu',
       'zacharie.deroo.etu/', 'zacharie.deroo.etu/noe.carpentier.etu'],
      dtype=object)

#### 3. Delete all rows of nebut

In [10]:
# # Before
print(len(df[df['actor'] == 'nebut/'])) 

# Apply
df = data_cleaning.delete_actor_lines(df, "nebut/")

# After
print(len(df[df['actor'] == 'nebut/']))

30
0

####  4. Split actor and binome into 2 columns

In [11]:
# Before
df['actor'].head(50)

0     abaly.oura.etu/
1     abaly.oura.etu/
2     abaly.oura.etu/
3     abaly.oura.etu/
4     abaly.oura.etu/
5     abaly.oura.etu/
6     abaly.oura.etu/
7     abaly.oura.etu/
8     abaly.oura.etu/
9     abaly.oura.etu/
10    abaly.oura.etu/
11    abaly.oura.etu/
12    abaly.oura.etu/
13    abaly.oura.etu/
14    abaly.oura.etu/
15    abaly.oura.etu/
16    abaly.oura.etu/
17    abaly.oura.etu/
18    abaly.oura.etu/
19    abaly.oura.etu/
20    abaly.oura.etu/
21    abaly.oura.etu/
22    abaly.oura.etu/
23    abaly.oura.etu/
24    abaly.oura.etu/
25    abaly.oura.etu/
26    abaly.oura.etu/
27    abaly.oura.etu/
28    abaly.oura.etu/
29    abaly.oura.etu/
30    abaly.oura.etu/
31    abaly.oura.etu/
32    abaly.oura.etu/
33    abaly.oura.etu/
34    abaly.oura.etu/
35    abaly.oura.etu/
36    abaly.oura.etu/
37    abaly.oura.etu/
38    abaly.oura.etu/
39    abaly.oura.etu/
40    abaly.oura.etu/
41    abaly.oura.etu/
42    abaly.oura.etu/
43    abaly.oura.etu/
44    abaly.oura.etu/
45    abaly.oura.etu/
46    abaly.oura.etu/
47    abaly.oura.etu/
48    abaly.oura.etu/
49    abaly.oura.etu/
Name: actor, dtype: object

In [12]:
# Apply
df = data_cleaning.split_actor_binome(df)

# After
df[['actor','binome']]

                     actor              binome
0           abaly.oura.etu
1           abaly.oura.etu
2           abaly.oura.etu
3           abaly.oura.etu
4           abaly.oura.etu
...                    ...                 ...
306941  zacharie.deroo.etu  noe.carpentier.etu
306942  zacharie.deroo.etu  noe.carpentier.etu
306943  zacharie.deroo.etu  noe.carpentier.etu
306944  zacharie.deroo.etu  noe.carpentier.etu
306945  zacharie.deroo.etu  noe.carpentier.etu

[306916 rows x 2 columns]

In [13]:
df['binome'].unique()

array(['', None, 'abderrahmen.ayadi.etu', 'hazem.hlioui.etu',
       'serigne.cisse.etu', 'ilian.briki.etu',
       'edohson-arnaud.guedou.etu', 'yasser.jad.etu',
       'nils.charfeddine-barbier.etu', 'nassim.belouar.etu',
       'rayane.denni.etu', 'aissatou-bobo.diallo.etu',
       'fadil.sani-labo.etu', 'anas.rsmouki.etu',
       'romann.szczepaniak.etu', 'mamadou-bachir.barry.etu',
       'sadia.muhammad.etu', 'hajar.amnay.etu', 'nayssam.benessalah.etu',
       'ismail.nejjar.etu', 'alpha-abdoulaye.diallo.etu',
       'thierno-abdoulaye.diallo2.etu', 'ghizlane.aissaoui.etu',
       'avsin.ata.etu', 'julien.buseyne.etu', 'igor.belyaev.etu',
       'elias.debab.etu', 'hamza.chebbah.etu', 'clement.sorge.etu',
       'antoine.bollen.etu', 'pierrick.cardoso.etu', 'mayas.bouhadda.etu',
       'safa-khawthar.draouche.etu', 'hugo.vandewalle2.etu',
       'youssef.airaki.etu', 'anass.saidi.etu', 'mohammed.abdennour.etu',
       'nolan.halluin.etu', 'mervin.kalistas.etu', 'boris.mutagoma.etu',
       'asmaa.saibi.etu', 'assia.mousselmal.etu', 'ibrahima.diallo8.etu',
       'imrane.mehenni.etu', 'imane.messali.etu', 'keba.thiam.etu',
       'elyna.belkacemi.etu', 'adama-eliya.avlah.etu',
       'mamadou-sellou.diallo.etu', 'antoine.vanhauwaert.etu',
       'eya.yahyaoui.etu', 'walid.farrash.etu', 'douae.ramdani.etu',
       'mehdi.rabi.etu', 'mohamed-sami.mousaid.etu', 'noa.gobaut.etu',
       'hugo.deschamps2.etu', 'ethan.duhot.etu', 'matthieu.bouin.etu',
       'elyes.guedria.etu', 'sokhna.dia2.etu',
       'jacques-lazare.diatta.etu', 'florian.heyte.etu',
       'elliot.launay.etu', 'jeremie.dhollande.etu', 'anis.medani.etu',
       'sami.mili.etu', 'anas.bouchlaghem.etu', 'nadjib.zoubir.etu',
       'pedro-luis.lock-benites.etu', 'alicia.zouadi.etu',
       'luc.duriez.etu', 'enzo.miuzzo.etu', 'mehdi.chaib-deraa.etu',
       'aymeric.amblanc.etu', 'mounir.achbad.etu', 'abdoulaye.nguere.etu',
       'adam.chikh-touami.etu', 'louis.warembourg.etu',
       'romain.balitout.etu', 'qassim.kahoul.etu',
       'dariya.kinadinova.etu', 'sami.boumiz.etu', 'said.dahmani.etu',
       'fawaaz.oyedotun.etu', 'enzo.dewez.etu',
       'anaba.hilary-williams.etu', 'mehmet.kucukkalfa.etu', 'MI1301',
       'MI1304', 'dantoire-lalle.namoni.etu', 'luc', 'yves.djegnon.etu',
       'gora.diop.etu', 'kotchi-ange-gedeon.kama.etu',
       'koffi.gantchou.etu', 'samuel.huret.etu', 'yanis.brahimi.etu',
       'amel.hadjloum.etu', 'thomas.desbuissons.etu', 'kilian.graye.etu',
       'thibault.maton.etu', 'manel.kracheni.etu', 'shirel.da-silva.etu',
       'mamadou.diallo9.etu', 'm-bah-ange-pascal.tanoh.etu',
       'paul.heroguel.etu', 'loucas.meganck.etu', 'ahmed.terfas.etu',
       'imad.berhoum.etu', 'enrick.debailleul.etu', 'rayane.asma.etu',
       'naim.abdellaoui.etu', 'samuel.scavone.etu', 'tarik.amirat.etu',
       'bilel.doggui.etu', 'mamadou.manga.etu', 'ibrahim.yahia.etu',
       'mohamed.mana.etu', 'nassim.abbad.etu', 'willy.nguyen.etu',
       'ahmed.bouziani.etu', 'florian.casteur-delpierre.etu',
       'yanko.lemoine.etu', 'abdallah.saint-ghislain.etu',
       'josselin.hebert.etu', 'henry.hebelamou.etu',
       'shema.mugambira.etu', 'ilyes.hadadi.etu', 'adame.chairi.etu',
       'oumou.diallo3.etu', 'ilyes.benferhat.etu', 'salim.rachdi.etu',
       'marion.le-guen.etu', 'alix.carton2.etu', 'pap-amath.thiam.etu',
       'aya.rhani.etu', 'mohamed-el-amine.samahri.etu',
       'faustine.descatoire.etu', 'lea.vannobel.etu',
       'hichame.haddou.etu', 'yastene.chemam.etu',
       'samy.yahia-cherif.etu', 'yanis.nabet.etu', 'manel.cherief.etu',
       'komivi.akpata.etu', 'malak.boudoh-mimun.etu', 'maodo.niang.etu',
       'fatoumata-bintou.traore.etu', 'hadjara.darou.etu',
       'lucile.viau.etu', 'andy.ba.etu', 'nassim.arbaoui.etu',
       'david.kahak.etu', 'noam.taibi.etu', 'noe.carpentier.etu'],
      dtype=object)

#### 5. Remove actors or binomes name

In [14]:
# Before in actor
count = (df['actor'] == 'nebut').sum()
print(f"The value appears {count} times for nebut.")

# Before in binome
count = (df['binome'] == 'luc').sum()
print(f"The value appears {count} times for luc.")

df = data_cleaning.delete_name_actor_binome(df, 'actor', 'nebut')
df = data_cleaning.delete_name_actor_binome(df, 'binome', 'luc')
    
# After in actor
count = (df['actor'] == 'nebut').sum()
print(f"The value appears {count} times for nebut.")

# After in binome
count = (df['binome'] == 'luc').sum()
print(f"The value appears {count} times for luc.")

The value appears 0 times for nebut.
The value appears 14 times for luc.
The value appears 0 times for nebut.
The value appears 0 times for luc.

#### 6. Replace None value by empty string

In [15]:
# Before
print(f"Total value of None in actor: {len(df[df['actor'].isna()])}")
print(f"Total value of None in binome: {len(df[df['binome'].isna()])}")

# Apply
df = data_cleaning.replace_None_by_str(df,'binome')

# After
print("After")
print(f"Total value of None in actor: {len(df[df['actor'].isna()])}")
print(f"Total value of None in binome: {len(df[df['binome'].isna()])}")

Total value of None in actor: 0
Total value of None in binome: 3756
After
Total value of None in actor: 0
Total value of None in binome: 0

#### 7. Replace joker

In [16]:
# Before
print(len(df[df['binome'] == 'MI1304']), len(df[df['binome'] == 'MI1301']))

jokers_real_name = {
    'MI1304': 'mariama-sere.sylla.etu',
    'MI1301': 'mariama-sere.sylla.etu'
}

# Apply
df = data_cleaning.replace_jokers(df, ['actor','binome'],jokers_real_name)

# After
print("After")
print(len(df[df['binome'] == 'MI1304']), len(df[df['binome'] == 'MI1301']))

52 445
After
0 0

#### 8. Cleaning manually

In [17]:
# Before
print(len(df[df['actor'] == 'anis.younes.etu']))

# Apply
df = data_cleaning.cleaning_manual_actors_2425(df, 'anis.younes.etu')

# After
print("After")
print(len(df[df['actor'] == 'anis.younes.etu@univ-lille.fr']))

2
After
0

In [18]:
# Retry the test to see the number of incorrects
incorrect = data_cleaning.not_a_correct_identifier(df)
incorrect

Series([], dtype: object)

In [19]:
# Save new df
io_utils.write_csv(df,INTERIM_DATA_DIR)

Directory is ok.
File saved.

### Read clean dataframe

In [20]:
df = io_utils.reading_dataframe(dir= INTERIM_DATA_DIR, file_name='actuer_nettoyage_2425.csv')

Directory is ok.

In [21]:
df['actor'].unique()

array(['abaly.oura.etu', 'abdallah.saint-ghislain.etu',
       'abdelrahmane.bendjeladjel.etu', 'abderrahmen.ayadi.etu',
       'abdoulaye.mbaye.etu', 'abdoulaye.nguere.etu',
       'adam.chikh-touami.etu', 'adam.oukzedou.etu', 'adam.sialiti.etu',
       'adama-eliya.avlah.etu', 'adame.chairi.etu', 'adem.kaloun.etu',
       'adnane.el-mazouni.etu', 'adrien.vetter.etu', 'ahmed.bouziani.etu',
       'ahmed.terfas.etu', 'ahmedzeidane.mohamedelmoctar.etu',
       'aissatou-bobo.diallo.etu', 'alban.gahide-fournier.etu',
       'alicia.zouadi.etu', 'alix.carton2.etu',
       'alpha-abdoulaye.diallo.etu', 'alpha-mahmoudou.diallo.etu',
       'amadou-madani.balde.etu', 'amadou.balde.etu', 'amel.hadjloum.etu',
       'amine.khadri.etu', 'anaba.hilary-williams.etu',
       'anaelle.brient.etu', 'anaelle.case.etu', 'anais.bilek.etu',
       'anas.bouchlaghem.etu', 'anas.en-nor.etu', 'anas.rsmouki.etu',
       'anass.saidi.etu', 'andy.ba.etu', 'ania.belaida.etu',
       'anis.bitari.etu', 'anis.medani.etu', 'antoine.bollen.etu',
       'antoine.hotin.etu', 'antoine.lherbier.etu',
       'antoine.vanhauwaert.etu', 'anton.dablement.etu',
       'asmaa.saibi.etu', 'assia.mousselmal.etu', 'augustin.derieux.etu',
       'aurelien.bithorel.etu', 'aurelien.dez.etu', 'avsin.ata.etu',
       'axel.flippe.etu', 'aya.rhani.etu',
       'ayao-landry-jeremie.dzossou-afanlete.etu', 'aymeric.amblanc.etu',
       'ayoub.el-khayari.etu', 'ben-magloire.hoessi.etu',
       'bilal.oualbagui.etu', 'bilal.ouazize.etu', 'bilel.doggui.etu',
       'bilel.taieb.etu', 'boris.mutagoma.etu', 'boubacar.barry.etu',
       'candice.billerait.etu', 'chaima.chakroun.etu',
       'chainez.boucherim--catry.etu', 'claire.tetart.etu',
       'clara.kombe.etu', 'clement.sorge.etu', 'dania.baroud.etu',
       'dantoire-lalle.namoni.etu', 'dario.bitri.etu',
       'dariya.kinadinova.etu', 'david.kahak.etu', 'demba.diao.etu',
       'djama.souleiman-abdi.etu', 'douae.ramdani.etu',
       'edohson-arnaud.guedou.etu', 'el-hadji-malick.gueye.etu',
       'elias.debab.etu', 'elliot.launay.etu', 'elliot.leroux.etu',
       'elyas.rabhiu.etu', 'elyes.guedria.etu', 'elyna.belkacemi.etu',
       'emeline.jonneaux-pantofel.etu', 'emma.souvestre.etu',
       'enrick.debailleul.etu', 'enzo.dewez.etu', 'enzo.miuzzo.etu',
       'ethan.duhot.etu', 'ethan.slowack.etu', 'eya.yahyaoui.etu',
       'eya.zeidi.etu', 'fadil.sani-labo.etu', 'fadila.taffa.etu',
       'farmata-sall.sow.etu', 'fatima.almohamed-alsadou.etu',
       'fatoumata-bintou.traore.etu', 'faustine.descatoire.etu',
       'fawaaz.oyedotun.etu', 'fayez.ben-bouali.etu',
       'florian.casteur-delpierre.etu', 'florian.heyte.etu',
       'gabriel.maatouk-dorlot.etu', 'ghizlane.aissaoui.etu',
       'grace-rochelde.louhanana.etu', 'guillaume.depelchin.etu',
       'hadja-maimouna.balde.etu', 'hadjara.darou.etu', 'hajar.amnay.etu',
       'hajar.zeaiter.etu', 'hamza.chebbah.etu', 'hazem.hlioui.etu',
       'helio.dequeker.etu', 'henry.hebelamou.etu', 'hichame.haddou.etu',
       'hichem.belabes.etu', 'hugo.deschamps2.etu', 'hugo.leleu.etu',
       'hugo.vandewalle2.etu', 'ibn-farrid.sama.etu', 'ibrahim.yahia.etu',
       'ibrahima-al-amine.diaw.etu', 'ibrahima.diallo8.etu',
       'ibrahima.diop.etu', 'ibrahima.sylla2.etu', 'igor.belyaev.etu',
       'ilian.briki.etu', 'ilyes.benferhat.etu', 'ilyes.hadadi.etu',
       'imad.berhoum.etu', 'imane.messali.etu', 'imrane.mehenni.etu',
       'ismail.nejjar.etu', 'ivan.mbonjo.etu',
       'jacques-lazare.diatta.etu', 'jean-mayes.zitouni.etu',
       'jeremie.dhollande.etu', 'josselin.hebert.etu',
       'jules.salandre.etu', 'julien.batrelle.etu', 'julien.buseyne.etu',
       'julien.choquet.etu', 'julien.deneubourg.etu',
       'kade-bhoye.wann.etu', 'kamal-deen-oloumide.savi.etu',
       'keba.thiam.etu', 'kellian.sory.etu', 'khadim.beye.etu',
       'kilian.graye.etu', 'koffi-john.evon.etu', 'koffi.gantchou.etu',
       'komi.dogbe.etu', 'komivi.akpata.etu',
       'kotchi-ange-gedeon.kama.etu', 'lansana.beavogui.etu',
       'lea.claire.etu', 'lea.vannobel.etu', 'lino.mallevaey.etu',
       'louane.deligny.etu', 'loucas.meganck.etu', 'louis.warembourg.etu',
       'luc.duriez.etu', 'lucile.viau.etu', 'lyna.boussahela.etu',
       'm-bah-ange-pascal.tanoh.etu', 'maeva.coppey.etu',
       'maeva.ochsenfeld.etu', 'magatte.mbathie.etu',
       'malak.boudoh-mimun.etu', 'malick-ndiaye.kone.etu',
       'mamadou-alpha.diallo2.etu', 'mamadou-bachir.barry.etu',
       'mamadou-sellou.diallo.etu', 'mamadou.barry8.etu',
       'mamadou.diallo9.etu', 'mamadou.manga.etu', 'mame-diarra.tall.etu',
       'mame-ngor.aw.etu', 'manel.cherief.etu', 'manel.kracheni.etu',
       'maodo.niang.etu', 'marcio.vieira-matos.etu', 'marion.le-guen.etu',
       'marko.yanovskyi.etu', 'maryam.hezzat.etu', 'massama.keita.etu',
       'massil.kichi.etu', 'matheo.facon.etu', 'matheo.paszkowski.etu',
       'mathis.thomas.etu', 'matthieu.bouin.etu', 'matthieu.misiak.etu',
       'maxence.magras.etu', 'maxime.mpungwe.etu', 'mayas.bouhadda.etu',
       'mehdi.chaib-deraa.etu', 'mehdi.rabi.etu', 'mehmet.kucukkalfa.etu',
       'mervin.kalistas.etu', 'merwan.sergent.etu',
       'michael.tankeu-bigna.etu', 'milan.caillot.etu',
       'mirdaas-alfa-kaza.alidou.etu', 'mohamed-el-amine.samahri.etu',
       'mohamed-nazim.ait-kaci.etu', 'mohamed-sami.mousaid.etu',
       'mohamed.belfadel.etu', 'mohamed.djafer.etu', 'mohamed.mana.etu',
       'mohamed.trougouty.etu', 'mohamed.zemmouri.etu',
       'mohammed.abdennour.etu', 'momar.niang.etu', 'mounir.achbad.etu',
       'mounir.zebboudji.etu', 'mugisha.nzakamwita.etu',
       'nadjib.zoubir.etu', 'naim.abdellaoui.etu', 'nassim.abbad.etu',
       'nassim.arbaoui.etu', 'nassim.belouar.etu', 'nathan.remoleux.etu',
       'nayad.senaici.etu', 'nayssam.benessalah.etu', 'ndongo.diao.etu',
       'nhungocanh.nguyen.etu', 'nicolas.raharinaivo.etu',
       'nils.charfeddine-barbier.etu', 'noa.gobaut.etu', 'noam.taibi.etu',
       'noe.carpentier.etu', 'noe.le-van-canh-dit-ban.etu',
       'nolan.chevalier.etu', 'nolan.halluin.etu', 'nourou.diouf.etu',
       'oscar.abidi.etu', 'oumou.diallo3.etu', 'oyawa.liza.etu',
       'pap-amath.thiam.etu', 'paul.heroguel.etu',
       'pedro-luis.lock-benites.etu', 'pierre.delecourt.etu',
       'pierrick.cardoso.etu', 'qassim.kahoul.etu',
       'raphael.crozat-moreau.etu', 'raphael.tafani.etu',
       'rayan.fortas.etu', 'rayane.asma.etu', 'rayane.denni.etu',
       'richard.kpande-adzare.etu', 'romain.balitout.etu',
       'romain.faidherbe.etu', 'romain.ruelle.etu', 'romane.deleau.etu',
       'romann.szczepaniak.etu', 'rosche-rostell.batchi-vouala.etu',
       'rose.pananceau.etu', 'ruben.cassin.etu', 'sabine.boukais.etu',
       'sadia.muhammad.etu', 'safa-khawthar.draouche.etu',
       'said.dahmani.etu', 'salem.el-bouhouti.etu', 'salim.rachdi.etu',
       'sami.boumiz.etu', 'sami.mili.etu', 'samir.fandi.etu',
       'samuel.huret.etu', 'samuel.scavone.etu', 'samy.yahia-cherif.etu',
       'serhii.ivkin.etu', 'serigne.cisse.etu',
       'shadrak-arthur.banouanina.etu', 'shema.mugambira.etu',
       'shirel.da-silva.etu', 'sokhna.dia2.etu',
       'taissir.el-hammouchi.etu', 'tarik.amirat.etu',
       'thibault.maton.etu', 'thierno-abdoulaye.diallo2.etu',
       'thierno.barry4.etu', 'thomas.desbuissons.etu',
       'timothe.devigne.etu', 'tristan.melchior.etu',
       'valentin.faust.etu', 'wail.ghouila.etu', 'walid.farrash.etu',
       'waylan.godfrey.etu', 'weeti-sharleen.akogbeto.etu',
       'willy.nguyen.etu', 'yadiradjen.mounien.etu', 'yanis.brahimi.etu',
       'yanis.gannar.etu', 'yanis.kharchi.etu', 'yanis.nabet.etu',
       'yanko.lemoine.etu', 'yasser.jad.etu', 'yastene.chemam.etu',
       'yohan.michel.etu', 'youssef.airaki.etu', 'yves.djegnon.etu',
       'zacharie.deroo.etu'], dtype=object)

### Clean **Filename** Field 
Process:
1. Replace None values in filename by ""
2. Split filename, extract the filename
3. Fill empty filename for each verbe (like Run.Program)

#### 1. Replace None values in filename by ""

In [22]:
#Before 
print(df['filename'].isnull().sum())

# Apply 
df = data_cleaning.replace_None_by_str(df,'filename')

#After
print(df['filename'].isnull().sum())

151183
0

#### 2. Split filename, extract the filename

In [23]:
# Before
df['filename'].head(50)

0
1       /home/l1/abaly.oura.etu/Downloads/puissance4.py
2
3
4            /home/l1/abaly.oura.etu/TDM 8/devinette.py
5            /home/l1/abaly.oura.etu/TDM 8/devinette.py
6
7     /home/l1/abaly.oura.etu/TDM 8/erreurs_boucles_...
8            /home/l1/abaly.oura.etu/TDM 8/devinette.py
9            /home/l1/abaly.oura.etu/TDM 8/devinette.py
10           /home/l1/abaly.oura.etu/TDM 8/devinette.py
11           /home/l1/abaly.oura.etu/TDM 8/devinette.py
12           /home/l1/abaly.oura.etu/TDM 8/devinette.py
13
14
15               /home/l1/abaly.oura.etu/TDM 8/while.py
16
17    /home/l1/abaly.oura.etu/Documents/iterables_fo...
18
19
20    /home/l1/abaly.oura.etu/Documents/iterables_fo...
21    /home/l1/abaly.oura.etu/TDM7*/iterable_indexat...
22
23
24
25
26
27
28
29
30
31            /home/l1/abaly.oura.etu/Downloads/ytdd.py
32            /home/l1/abaly.oura.etu/Downloads/ytdd.py
33            /home/l1/abaly.oura.etu/Downloads/ytdd.py
34            /home/l1/abaly.oura.etu/Downloads/ytdd.py
35            /home/l1/abaly.oura.etu/Downloads/ytdd.py
36            /home/l1/abaly.oura.etu/Downloads/ytdd.py
37            /home/l1/abaly.oura.etu/Downloads/ytdd.py
38            /home/l1/abaly.oura.etu/Downloads/ytdd.py
39            /home/l1/abaly.oura.etu/Downloads/ytdd.py
40            /home/l1/abaly.oura.etu/Downloads/ytdd.py
41            /home/l1/abaly.oura.etu/Downloads/ytdd.py
42            /home/l1/abaly.oura.etu/Downloads/ytdd.py
43            /home/l1/abaly.oura.etu/Downloads/ytdd.py
44            /home/l1/abaly.oura.etu/Downloads/ytdd.py
45
46
47
48
49
Name: filename, dtype: object

In [24]:
# Apply
df['filename'] = data_cleaning.extract_filename(df['filename'])

In [25]:
# After
df['filename'].head(50)

0
1                puissance4.py
2
3
4                 devinette.py
5                 devinette.py
6
7     erreurs_boucles_while.py
8                 devinette.py
9                 devinette.py
10                devinette.py
11                devinette.py
12                devinette.py
13
14
15                    while.py
16
17            iterables_for.py
18
19
20            iterables_for.py
21      iterable_indexation.py
22
23
24
25
26
27
28
29
30
31                     ytdd.py
32                     ytdd.py
33                     ytdd.py
34                     ytdd.py
35                     ytdd.py
36                     ytdd.py
37                     ytdd.py
38                     ytdd.py
39                     ytdd.py
40                     ytdd.py
41                     ytdd.py
42                     ytdd.py
43                     ytdd.py
44                     ytdd.py
45
46
47
48
49
Name: filename, dtype: object

#### 3. Fill empty filename for Run.Test

In [26]:
df[df['verb']=='Run.Test']['filename'].unique()

array(['devinette.py', 'ytdd.py', 'iterable_indexation.py',
       'experimentations_fichiers.py', 'puissance4.py',
       'erreurs_boucles_while.py', 'iterables_for.py', 'tictactoe.py',
       'fichiers.py', 'erreurs_aliasing.py',
       'erreurs_boucles_while_suite.py', 'parcours_interrompu.py',
       'erreurs_cond().py', 'conditionnels.py', 'manipulations.py',
       'OURATDM3.py', 'erreurs_cond.py', 'conditionnelles.py',
       'erreurs_cond(1).py', 'categories.py', 'pendu.py', 'fichier.py',
       'while.py', 'imprimerie.py', 'jeu_421.py', 'TP-PROG.py',
       'erreurs_multiples.py', 'booleens.py', 'pour_aller_plus_loin.py',
       'complementaire.py', 'suplémentaire.py', 'age.py',
       'controleTPi.py', 'ab.py', 'abderrahmen ayadi prog.py',
       'programation.py', 'prog.py', 'erreur.py', 'asba.py',
       'fonctions.py', 'exemple_simple.py', 'vzvzfzfzz.py',
       'echappement.py', 'interactions_mystere.py', 'premier_script.py',
       'tuyt.py', 'fonctions .py', 'pour_debogeur.py', 'brouillon.py',
       'exo_complementaire.py', 'exo_1.py', 'perelman.py', 'polynomes.py',
       'TP booleen.py', 'controleTP1.py',
       'fonctions.adnane.el_mazouni.py', 'TP1 Bis deboggeur.py',
       'debogueur TP1 bis 2.py', 'jeu_421 AHMED ET NASSIM FINAL.py',
       'affichage.py', 'TP6 complémentaire.py', 'booléen.py', 'tp4.py',
       'tp3.py', 'tp3 (3).py', 'DS 2023-2024.py', 'tp8.py', 'tp9 (2).py',
       'tp7.py', 'tp9.py', 'mesures.py', 'imbriquees.py', 'binaire.py',
       'debogueur-for.py', 'parcours_interrompu (1).py', 'TP10.py',
       'tic-tac-toc.py', 'TICTAC.py', 'manipulation08.py',
       'exercice de manipulation  09.py', 'while09.py',
       'booleen_plusloin.py', 'tic_tac_toe.py', 'plus_loin.py',
       'jeux_algo_f1.py', 'binairo.py', 'saisies_diverses.py',
       'f2_jeux_algo.py', 'echauffement.py', 'mesure.py',
       'tp_fonctions.py', 'tp_fonctions_complementaire.py', 'jeu_nim.py',
       'Conditionelle_prog.py', 'conditionnelle_compl.py',
       'booleens_manipulation.py', 'for_complementaires.py',
       'booleens_prog.py', 'aller_plus_loin.py', 'Programme_principal.py',
       'interactions_prog.py', 'fonctions_manipulatiuons.py',
       'fonctions (1).py', 'manipulation.py',
       'exercicefonctionstermines.py', 'activite_range.py',
       'ProgrammaionTDM2.py', 'exercicedeprog.py',
       'exercicecomplementaire.py', 'exercicecomplementaires.py',
       'saison.py', 'td2.py', 'tdm semaine 9.py', 'tdm semaine 3.py',
       'erreurs tp semaine 3.py', 'semaine 3 tp.py',
       'semaine 4 partie 2.py', 'test td prog.py', 'tp semaine 4.py',
       'semaine 4.py', 'semaine 7.py', 'tdm prog sem 8.py',
       'td semaine 6.py', 'Tp_Iterables_et_boucle_for_brouillon.py',
       'iterables_for_brouillon.py', 'Tp8_brouillon.py',
       'Parcours_interrompu_brouillon.py', 'journal_de_bord_brouillon.py',
       'experimentation_fichier.py', 'n° 1.py', 'gghuik.py', 'tp2test.py',
       'iterable_indexation1.py', 'a.py', 'aa.py',
       'pour_aller_plus_loin_prog3.py', 'categories_cond.py',
       'tp_iterables-indexation.py', 'iterable_indexationvf.py',
       'tictactoe (1).py', 'parcours_interrompu (1) (1).py',
       'pour_debogueur.py', 'EXERCICES_BOOL.py', 'Booléens.py',
       'Exos complémentaires.py', 'TD_9.py', 'iterable_for.py', 'TP3.py',
       'saison_main.py', 'erreurs.py', 'iterable_indexation_salle_tp.py',
       'tst.py', 'while (1).py', 'erreurs_cTPi (1) (1).py',
       'iterable_indexation_perso.py', 'jeu_2048.py', 'tp_2_prog.py',
       'tdm_prog_bool.py', 'exooooautres.py', 'TP11.py', 'TP09.py',
       'hexa.py', 'complementaire_condition.py', 'Bool prog.py',
       'Option RR 1.py', 'masque.py', 'CODE TD2.py', 'fonction.py',
       'binairo (3).py', 'noolean.py', 'errueur multiples.py',
       'erreur_boucle_while.py', 'interaction_mystere.py',
       'debogueur_for.py', 'cercle.py', 'poly.py', 'mesure1.py',
       'calcul_interets.py', 'booleens(1).py', 'puissance 4.py',
       'zasedfghj kcxl.py', 'moyenne entiere 1109.py', 'heure2minute.py',
       'salutation.py', 'partage bonbon.py', 'tp_booleens.py',
       'tp 1109.py', 'complementaires_Itérables_et_boucles_for.py',
       'while_complementaires.py', 'exercices_complementaire_booleen.py',
       'TIC_TAC_TOE.py', 'puissance_4_2.py', 'test.py',
       'TP 11 fichiers.py', 'jeu_Nim.py', 'tictactoe-2.py',
       'fonctions-3.py', '1.py', 'erreurs_cTPi.py', 'iterables_for-1.py',
       'TP_aliasing_exercice_de_manipulation.py', 'tp_02.py',
       'note_UE.py', 'complemnatires-tp6.py', 'tdm11.py',
       'booleens (1).py', 'complementaires.py',
       'erreurs_multiples (1).py', 'Tp à rendre: affiachge.py',
       'TP à rendre: iterable_indexation (1).py', 'polynomes (2).py',
       'TP à rendre: iterables_for (1).py', 'Projet jeu_2048.py',
       'rendu TP while.py', 'exos_comp.py',
       'configurations_init_jeu_vie.py', 'repetition.py',
       'moyenne_entiere.py', 'Exo_comp.py', '2048.py',
       'exercice complementaire.py', 'booleens (3).py',
       'complémentaires.py', 'iterable_indexation (1).py',
       'TDM fonction prog.py', 'polynome.py', 'exo.py',
       'manipulations_cTPi.py', 'demo_CM8.py', 'elements_consecutifs.py',
       'tictactoe2.py', 'exo1.py', 'location.py',
       'puissance 4 version douae.py', 'kkkkkkk.py', 'son.py', 'td_3.py',
       'ed_el.py', 'l.py', 'exos_bool.py', 'chaine de charactere.py',
       'renforce recherche premiere fiche.py', 'somme_nombres.py',
       'pour-aller-plus-loin-boucles_et_iterables.py', 'projet_2048.py',
       'TD-FINI-Elliot_launay-exos-prorammation.py',
       'TD-exercices-de-programmation-ELLIOT_LAUNAY.py',
       'TD-Exercices-supplémentaires.py', 'maximum.py',
       'tp2_prog_leroux.py', 'debug.py',
       'exercice complementaire iterable.py', 'Complémentaire.py',
       'conditionnelle.py', 'jeu gain.py', 'ReadME.py', 'Readme.py',
       'tp2.py', 'p4.py', 'tp10 manipulation.py', 'demo_CM11.py',
       'iterables_for .py', 'demo_CM7.py', 'revision.py', 'essaye.py',
       'binairo (2).py', 'exxx.py', 'manipulation (suite).py', 'prog2.py',
       'manipulations (1).py', 'tictactoe (1) (1).py',
       'tictactoe (1) (1) (1).py', 'booleens2.py', 'imprimerie .py',
       'conditionnelles (1).py', 'fwz.py', 'jkhgg.py', 'rep.py',
       'tdm_2.py', 'config_binairo.py', 'bonus.py',
       'pour-aller-plus-loin.py', 'Fichiers.py', 'programmation.py',
       'fonctions_polynome.py', 'erreurs (1).py', 'Tp3-prog-louhanana.py',
       'TD_1.py', 'Renforce_recherche_Exo4.py', 'TD_3.py',
       'Renforce_recherche_Feuille2.py', 'TP_6_PourAllerPlusLoin.py',
       'TP_fonctions_N1.py', 'TP_1_PourAllerPlusLoin.py',
       'Boucle while.py', 'erreur_multiples.py',
       'erreur_boucles_while.py', 'debogueur.py',
       'erreur_boucles_while_suite.py',
       'Ex de Programmation Conditionnelles.py',
       'Ex de manipulation Conditionnelles.py', 'exo_comple.py',
       'eexo_fichiers.py', 'Indexation.py', 'bool.py',
       'Exercice de programmation.py', 'erreur_while.py',
       'Exercice complementaires.py', 'Exercice manipulation.py',
       'while (2).py', 'iterable_indexation (2).py',
       'Devoir Maison 1 programmation.py',
       'iterable_indexation(partiel).py',
       'parcours_interrompu (1) (2).py', 'erreur_aliasing_correction.py',
       'polynôme.py', 'exo_progTP4.py', 'manipulation_tp7.py',
       'exo_progtp3.py', 'devinettes.py', 'Fonction.py', 'moyenne.py',
       'moyenne_ponderee.py', 'moyenne_entiere2.py', 'jour2heure.py',
       'en_minutes.py', 'manipulationTP4.py',
       'erreurs_boucles_while_suit.py', 'manipulationTP3.py',
       'premier_programme.py', 'puissance4.py.py',
       'exercices_complementaires_fonction.py', 'tp1.py', 'tp_3.py',
       'tp_2.py', 'progtpiterable.py', 'manipulations1.py',
       'programation1.py', 'exo_de_prog.py', 'programation3.py',
       'complementiare.py', 'tdm44.py', 'tdm4.py', 'tic tac toe.py',
       'bool_prog.py', 'iterable_indexation_essaie.py', 'while .py',
       'parcours_interrompu (3).py', 'fonctions (3) (2).py',
       'fonctions (3) (1).py', 'controle1.py', 'While.py', 'tp1-2.py',
       'tyfyt.py', 'itérables_for.py', 'chaine_rep.py', 'TDM08.py',
       'armstrong.py', 'booléens.py', 'TD_debogueur.py',
       'experimentations_fichier.py', 'tictactoe.11.py', 'ohooo.py',
       'prog 6.py', 'TDM3-PROG-loin.py', 'echauf.py', 'TDM2-PROG-loin.py',
       'pour_aller_plus_loin_boucle.py', 'ProjetTICTACTOE.py',
       'ProjetPuissance4.py', 'Complémentaires_itérables.py',
       'bandit_manchot.py', 'morpion.py', 'aller_plus_loin_7.py',
       'while2.py', 'qdsffdsqw.py', 'note_Ue.py', 'fonctions_comp.py',
       'tp09.py', 'iterable_indexation_refaire.py', 'comp.py', 'TDM3.py',
       'complement_tdm6.py', 'td cond.py', 'conditionnelles(1).py',
       'erreur_cond.py', 'dm_kiliangraye.py', 'd.py',
       'erreurs_boucles_while_suite3.py', 'parcours_interrompu3.py',
       'tictactoe .py', 'element_consecutifs.py', 'predicat.py',
       'exo de manipulation6.py', 'conditionnel.py', 'rev.py',
       'imbrique.py', 'mo.py', 'iterable_indexation (3).py',
       'exercice complementaire sur les for.py',
       'iterable_indexation (3) (2).py', 'parcours.py', 'while(1).py',
       'parcours_interrompu(1).py', 'boucles while suite.py',
       'Itérables et boucles for.py', 'jeu tic tac toe.py',
       'Complémentaires.py', 'td manipulation.py', 'td prog fonction.py',
       '1er exos.py', 'puissance_4.py', 'type_booleen.py',
       'Programmation.py', 'seuil.py', 'puissance4_maton_viau.py',
       'parcours_interrompu_maton_viau.py', 'iterables_for_maton_viau.py',
       'iterable_indexation_maton_viau.py', 'tictactoe_maton_viau.py',
       'fonctions_viau_lucile_maton_thibault.py',
       'erreurs_aliasing_maton_viau.py',
       'erreurs_boucles_while_suite_maton_viau.py',
       'erreurs_boucles_while_maton_viau.py', 'devinette_maton_viau.py',
       'while_maton_viau.py', 'binairo_maton_viau.py',
       'jeu_nim_maton_viau.py', 'python.py', 'entrainement.py',
       'tp3-programmation.py', 'test tp8.py', 'main.py', 'outil.py',
       'Condition.py', 'Instruction Conditionnelle.py',
       'devinette_boucle_while.py', 'erreurs_CTPf.py', 'f.py',
       'comptage.py', 'a rendre.py', 'test4.py', 'manip4_categories.py',
       'tp4pascale.py', 'premierscript.py', 'TP2_foctions.py',
       'fonctions (4).py', 'parcours_interrompu-2.py',
       'erreurs_cTPi (1).py', 'controle1 (1).py', 'toto.py', 'rien.py',
       'Puissance4_BP.py', 'TDM4.py', 'entrainement_ds1.py',
       'semaine-6.py', 'iterables_for (1).py', 's.py', 'zebi.py',
       'CM prog 8.py', 'recherche_semaine_5.py', 'realfonctions.py',
       'n.py', 'Aller_plus_loin.py', 'Exo_tp2.py', 'erreures_python.py',
       'Partie_programmation.py.py', 'PRGM1.py',
       'iterable_indexation1 (1) (1).py', 'tectonic.py',
       'whilerange (1).py', 'iterables_for (1) (1).py', 'TDM6.py',
       'TP1.py', 'Fonctions.py', 'Booléen.py', 'TDM8.py', 'TDM9.py',
       'TDM7.py', 'Puissance4.py', 'EXO_cour.py', 'Convertion binaire.py',
       'parcours_interrompu_test.py', 'manip.py',
       'iterable_et boucle_for.py', 'progboolen.py', 'tp aliasing.py',
       'TP 2048.py', 'boucle_prog.py', 'conditionnelles .py',
       'ex complémentaire_1.py', 'aller_plus_loin 1.py',
       'renforcé recherche     séance 1.py', 'erreure alyaising.py',
       'conditionnelles (2).py', 'zzzz.py', 'sss.py', 'es.py',
       'conditionnell.py', 'conditionnells.py', '111.py', 'connelles.py',
       'booleen.py', 'Tictactoe_final_version.py', '456.py', 'ssss.py',
       'demo_CM9.py', 'README.py', 'eee.py', 'td10.py', 'TD9.py', 'fz.py',
       'trying.py', 'testingforsmth.py', 'modelToFollow.py', 'TD.py',
       'TD2.py', 'TD6.py', 'TD3.py', 'TD4.py', 'TP9.py', 'tictactoe 3.py',
       'exercices_comp.py', 'TP7.py', 'iterable-for.py', 'z.py',
       'Boucles while, suite.py', 'conditio_tp.py', 'tp_prog_bool.py',
       'TP revision.py', 'tp manip.py', 'iterable.py', 'fichierdemo.py',
       'binairoooooo.py', 'parcours_whilefor.py', 'S1.py',
       'tdm prog bool.py', 'essai_location.py', '421.py', 'cpt2.py',
       'sm9tst.py', 'demo_CM10.py', 'erreurs_aliasing (1).py',
       'Rendu_cpt2.py', 'puissance4 (1).py', 'jeu_nim (1).py',
       'cpt2 rendu.py', 'main2.py', 'main4.py', 'fichers.py',
       'tp fonction2.py', 'tp fonction.py', 'sdq.py', 'binairo (1).py',
       'Exercices complémentaires.py', 'savepourdebogguer.py',
       'TRAVAILLE AHMED NASSIM.py', 'manipulations partiel .py',
       'MANIPULATION BELLOUAR.py', 'manim.py', 'TP2 partiel.py',
       'fonctions2.py', 'game_2048.py', 'graphical_2048.py',
       'TP_booléens.py', 'programme_convert_impert_to_cm.py',
       'fonctions (2).py', 'parcours_interrompu (4).py', 'repititon.py',
       'prog_tp_fonction_2.py', 'PuissanceWithoutClass.py', 'calculPI.py',
       'tp_for_plusloin.py', 'exo_manipulation.py',
       'pourAllerPlusLoin.py', 'PI.py', 'AutreEx.py',
       'jeu- du- tictactoe.py', 'tictactoe_2711.py', 'g.py',
       'categories (1).py', 'jeu_du_bandit_manchot.py', 'ctp2_prog_11.py',
       'pour aller plus loin.py', 't.py', 'puissance4(2).py', 'pred.py',
       'borrar.py', 'TP.py', 'mesurre.py', 'TP4_LOCKB_HEBELAMOU.py',
       'fonct-myst.py', 'fonction_mystere.py', 'interactions_mysteres.py',
       'fonction mystere.py', 'debogeur.py', 'test1.py', 'test2.py',
       'test3.py', 'test3p2.py', 'gradient.py', 'final.py',
       'premier-script.py', 'moyenneponderee.py', 'message.py',
       'bonbons_par_enfants.py', 'concatenation.py',
       'moyenneentiereponderee.py', 'iterables_for (2).py', 'tdm2.py',
       'tdm3.py', 'exo_prog.py', 'jeu_vie.py', 'td1.py',
       'tictactoe-copie.py', 'CTP.py',
       'TP_Variables_expressions_instructions.py', 'imperial2metrique.py',
       'Tp_comple.py', 'tp_fichiers.py', 'complaimentaires.py',
       'ds_inter.py', 'bandit_monchot.py', 'XO.py', 'pour_aller_loin.py',
       'exo_complementaires.py', 'tp2_prog_boukais.py',
       'conditionnelles safa.py', ',ùmk,nùk,.py',
       'parcours_interrompu_safaa (1).py', 'exercice.py', 'tp 1.py',
       'ex_com_iterable.py', 'fonctions1.py', 'parcours_interrompu1.py',
       'tp prog.py', 'TP PROG functions.py', 'ex.py', 'td-bool-pt2.py',
       'tictactoev2.py', '3bisemetp.py', 'parcours_interrompu2.py',
       '2eme_tp.py', 'prog_tp07.py', 'iterables_boucles.py',
       'parcours_interrompue.py', 'huy.py',
       'PROG BOOL MUGAMBIRA SHEMA.py', 'td02.fonctions.py',
       'age_en_seconde.py', 'iterable_indexation-3.py',
       'tictactoe-2-2.py', 'perimetre_triangle_Lucile_viau.py',
       'boolens.py', 'indexation.py', 'iterable_indexation-2.py',
       'jeu_421 (1).py', 'gghhqq.py', 'mesure_global.py',
       'Tic tac toe.py', 'Tic tac toe_V2.py', 'wgr.py', 'len.py',
       'while (copy).py', 'test elyes.py', 'Programmation3$.py',
       'iterables_for_comp.py', 'tp_programmation_bool.py', 'RR_1.py',
       'tp6_pour_aller_plus_loin.py', 'tpfichier.py', 'jeeu_nim.py',
       'tdm_programation_Yanis_Marko.py', 'iterable_indexztion.py',
       'programe1.py', 'exo  comp.py', 'tic-tac-toe.py',
       'jeu_de_la_vie.py', 'semaine 6 yasser.py', 'prog_tp11.py',
       'Exercices_de_manipulation_TDM4.py',
       'Exercices_de_programmation_Instruction conditionnelle.py',
       'exercices_de_prog.py', 'exo_2_executer_le contenu.py',
       'exercices_de_proggramation.py', 'itérables.py', 'TP2-airaki.py',
       'TP 2 .py', 'RR1.py'], dtype=object)

In [27]:
print(df[df['verb']=='Run.Test']['filename'].isna().sum())
print((df[df['verb']=='Run.Test']['filename'] == '').sum())

0
0

There is no Nan or empty strings, OK for filename of Run.Test

#### 3. Fill empty filename for Run.Program

In [28]:
# Before
total       = len(df[df['verb']=='Run.Program'])
total_nan   = df[df['verb']=='Run.Program']['filename'].isna().sum()
total_empty = (df[df['verb']=='Run.Program']['filename'] == '').sum()

print(f"Total rows of Run.Program                  : {total}")
print(f"Total rows of Nan in Run.Program           : {total_nan}")
print(f"Total rows of empty strings in Run.Program : {total_empty}")

Total rows of Run.Program                  : 54352
Total rows of Nan in Run.Program           : 0
Total rows of empty strings in Run.Program : 54352

All values of filename for the rows where verb == Run.Program are an empty string.

In [29]:
# Fill by commandRan
mask = df['verb'] == 'Run.Program'
df.loc[mask, 'filename'] = data_cleaning.extract_filename_from_commandRan_Run_Program(df.loc[mask, 'commandRan'])

In [30]:
# After
total_empty = (df[df['verb']=='Run.Program']['filename'] == '').sum()

print(f"Total rows of empty strings in Run.Program : {total_empty}")

Total rows of empty strings in Run.Program : 5791

The number of empty strings reduced from 54352 to 5791 thanks to commandRan.

In [31]:
df[df['verb']=='Run.Program'][['filename','commandRan']].head(50)

                           filename                             commandRan
22                                               %Run -c $EDITOR_CONTENT\n
23                                               %Run -c $EDITOR_CONTENT\n
24                                               %Run -c $EDITOR_CONTENT\n
25                                               %Run -c $EDITOR_CONTENT\n
26                                               %Run -c $EDITOR_CONTENT\n
27                                               %Run -c $EDITOR_CONTENT\n
28                                               %Run -c $EDITOR_CONTENT\n
29                                               %Run -c $EDITOR_CONTENT\n
30                                               %Run -c $EDITOR_CONTENT\n
45                          ytdd.py                         %Run ytdd.py\n
46                          ytdd.py                         %Run ytdd.py\n
47                          ytdd.py                         %Run ytdd.py\n
48                          ytdd.py                         %Run ytdd.py\n
49                          ytdd.py                         %Run ytdd.py\n
50                          ytdd.py                         %Run ytdd.py\n
51                          ytdd.py                         %Run ytdd.py\n
102    experimentations_fichiers.py    %Run experimentations_fichiers.py\n
103    experimentations_fichiers.py    %Run experimentations_fichiers.py\n
107    experimentations_fichiers.py    %Run experimentations_fichiers.py\n
120        erreurs_boucles_while.py        %Run erreurs_boucles_while.py\n
125        erreurs_boucles_while.py        %Run erreurs_boucles_while.py\n
126        erreurs_boucles_while.py        %Run erreurs_boucles_while.py\n
127        erreurs_boucles_while.py        %Run erreurs_boucles_while.py\n
362                   puissance4.py                   %Run puissance4.py\n
365                   puissance4.py                   %Run puissance4.py\n
404                     fichiers.py                     %Run fichiers.py\n
409                     fichiers.py                     %Run fichiers.py\n
410                     fichiers.py                     %Run fichiers.py\n
411                     fichiers.py                     %Run fichiers.py\n
417                     fichiers.py                     %Run fichiers.py\n
420                     fichiers.py                     %Run fichiers.py\n
421                     fichiers.py                     %Run fichiers.py\n
423    experimentations_fichiers.py    %Run experimentations_fichiers.py\n
424    experimentations_fichiers.py    %Run experimentations_fichiers.py\n
425    experimentations_fichiers.py    %Run experimentations_fichiers.py\n
426    experimentations_fichiers.py    %Run experimentations_fichiers.py\n
427    experimentations_fichiers.py    %Run experimentations_fichiers.py\n
428    experimentations_fichiers.py    %Run experimentations_fichiers.py\n
429    experimentations_fichiers.py    %Run experimentations_fichiers.py\n
430    experimentations_fichiers.py    %Run experimentations_fichiers.py\n
431    experimentations_fichiers.py    %Run experimentations_fichiers.py\n
432    experimentations_fichiers.py    %Run experimentations_fichiers.py\n
433    experimentations_fichiers.py    %Run experimentations_fichiers.py\n
434    experimentations_fichiers.py    %Run experimentations_fichiers.py\n
435    experimentations_fichiers.py    %Run experimentations_fichiers.py\n
436    experimentations_fichiers.py    %Run experimentations_fichiers.py\n
437    experimentations_fichiers.py    %Run experimentations_fichiers.py\n
441                   puissance4.py                   %Run puissance4.py\n
442                   puissance4.py                   %Run puissance4.py\n
550  erreurs_boucles_while_suite.py  %Run erreurs_boucles_while_suite.py\n

In [32]:
# Fill with P_codeState for the rest.
mask = (df['verb'] == 'Run.Program') & (df['filename'] == '')
df.loc[mask, 'filename'] = df.loc[mask, 'P_codeState'].map(data_cleaning.extract_filename_from_P_codestate_Run_Program)

In [33]:
# After
total_empty = (df[df['verb']=='Run.Program']['filename'] == '').sum()

print(f"Total rows of empty strings in Run.Program : {total_empty}")

Total rows of empty strings in Run.Program : 4623

Empty strings reduced from 5791 to 4623 thanks to P_codeState.

In [34]:
df[df['verb']=='Run.Program'][['filename','P_codeState']].head(50)

,filename,P_codeState
22,premieres_occurrences.py,"def premieres_occurrences(s:str):\n """""" pre..."
23,premieres_occurrences.py,"def premieres_occurrences(s:str):\n """""" pre..."
24,premieres_occurrences.py,"def premieres_occurrences(s:str):\n """""" pre..."
25,premieres_occurrences.py,"def premieres_occurrences(s:str):\n """""" pre..."
26,premieres_occurrences.py,"def premieres_occurrences(s:str):\n """""" pre..."
27,premieres_occurrences.py,"def premieres_occurrences(s:str):\n """""" pre..."
28,premieres_occurrences.py,"def premieres_occurrences(s:str):\n """""" pre..."
29,premieres_occurrences.py,"def premieres_occurrences(s:str):\n """""" pre..."
30,premieres_occurrences.py,"def premieres_occurrences(s:str):\n """""" pre..."
45,ytdd.py,"def premieres_occurrences(s:str):\n """""" pre..."
46,ytdd.py,"def premieres_occurrences(s:str):\n """""" pre..."
47,ytdd.py,"def premieres_occurrences(s:str):\n """""" pre..."
48,ytdd.py,"def premieres_occurrences(s:str):\n """""" pre..."
49,ytdd.py,"def premieres_occurrences(s:str):\n """""" pre..."
50,ytdd.py,"def premieres_occurrences(s:str):\n """""" pre..."
51,ytdd.py,"def premieres_occurrences(s:str):\n """""" pre..."
102,experimentations_fichiers.py,"f1 = open('fichier1.txt', 'w')\nf1.write('bla1..."
103,experimentations_fichiers.py,"f1 = open('fichier1.txt', 'w')\nf1.write('bla1..."
107,experimentations_fichiers.py,"f1 = open('fichier1.txt', 'w')\nf1.write('bla1..."
120,erreurs_boucles_while.py,# L1 MI S1 - Prog\n# TP exos de manipulation -...
125,erreurs_boucles_while.py,# L1 MI S1 - Prog\n# TP exos de manipulation -...
126,erreurs_boucles_while.py,# L1 MI S1 - Prog\n# TP exos de manipulation -...
127,erreurs_boucles_while.py,# L1 MI S1 - Prog\n# TP exos de manipulation -...
362,puissance4.py,"# Compléter ici (noms, groupe, contenu fichier..."
365,puissance4.py,"# Compléter ici (noms, groupe, contenu fichier..."
404,fichiers.py,"\n\n\nf1 = open('fichier1.txt', 'w')"
409,fichiers.py,"\n\n\nf1 = open('fichier1.txt', 'w')\ntouch fi..."
410,fichiers.py,"\n\n\nf1 = open('fichier1.txt', 'w')\n"
411,fichiers.py,"\n\n\nf1 = open('fichier1.txt', 'w')\n"
417,fichiers.py,"\n\n\nf1 = open('fichier1.txt', 'w')\nf1.write..."
420,fichiers.py,"\n\n\nf1 = open('fichier1.txt', 'w')\nf1.write..."
421,fichiers.py,"\n\n\nf1 = open('fichier1.txt', 'w')\nf1.write..."
423,experimentations_fichiers.py,"f1 = open('fichier1.txt', 'w')\n"
424,experimentations_fichiers.py,"f1 = open('fichier1.txt', 'w')\n"
425,experimentations_fichiers.py,"f1 = open('fichier1.txt', 'w')\nf1.write('bla1..."
426,experimentations_fichiers.py,"f1 = open('fichier1.txt', 'w')\nf1.write('bla1..."
427,experimentations_fichiers.py,"f1 = open('fichier1.txt', 'w')\nf1.write('bla1..."
428,experimentations_fichiers.py,"f1 = open('fichier1.txt', 'w')\nf1.write('bla1..."
429,experimentations_fichiers.py,"f1 = open('fichier1.txt', 'w')\nf1.write('bla1..."
430,experimentations_fichiers.py,"f1 = open('fichier1.txt', 'w')\nf1.write('bla1..."
431,experimentations_fichiers.py,"f1 = open('fichier1.txt', 'w')\nf1.write('bla1..."
432,experimentations_fichiers.py,"f1 = open('fichier1.txt', 'w')\nf1.write('bla1..."
433,experimentations_fichiers.py,"f1 = open('fichier1.txt', 'w')\nf1.write('bla1..."
434,experimentations_fichiers.py,"f1 = open('fichier1.txt', 'w')\nf1.write('bla1..."
435,experimentations_fichiers.py,"f1 = open('fichier1.txt', 'w')\nf1.write('bla1..."
436,experimentations_fichiers.py,"f1 = open('fichier1.txt', 'w')\nf1.write('bla1..."
437,experimentations_fichiers.py,"f1 = open('fichier1.txt', 'w')\nf1.write('bla1..."
441,puissance4.py,"# Compléter ici (noms, groupe, contenu fichier..."
442,puissance4.py,"# Compléter ici (noms, groupe, contenu fichier..."
550,erreurs_boucles_while_suite.py,"# MI S1 - Prog\n# 2ème semaine boucles while, ..."

In [35]:
# Test for values with different pattern or empty string in filename of Run.Program
pattern = re.compile(r'^[\w\-]+\.py$') # Pattern : name(any number or space).py

filenames       = df[df['verb']=='Run.Program']['filename']
invalid_indices = filenames[~filenames.apply(lambda val: isinstance(val, str)  and bool(pattern.fullmatch(val.strip())))].index # Extract invalid index

mask = (df['verb'] == 'Run.Program') & (df['filename'] == '')

invalid_indices = set(invalid_indices) - set(df.loc[mask,'filename'].index) # Remove empty strings

print(f"Total rows    : {len(df[df['verb']=='Run.Program']['filename'])}")
print(f"Invalid rows  : {len(invalid_indices)}")
print(f"Empty strings : {len(df.loc[mask,'filename'])}")

Total rows    : 54352
Invalid rows  : 3643
Empty strings : 4623

From 54352 rows of Run.program, there are 3643 rows which doesn't have the same pattern as name.py in filename; and 4623 rows are empty string in filename.

In [36]:
# Check what are these 3643, first use unique() on their filename to reduces the number of redundent values.
unique_invalid_value = df.loc[list(invalid_indices)]['filename'].unique()
len(unique_invalid_value), unique_invalid_value

(236,
 array(["'itérables.py'", "'renforcé recherche1.py'",
        "'parcours_interrompu (1).py'", "'booléens.py'",
        "'Option RR 1.py'", "'jeu- du- tictactoe.py'",
        "'iterable_indexation (3) (2).py'", "'RR 22_11.py'",
        "'jeu tic tac toe.py'", "'puissance 4.py'", "'tictactoe (1).py'",
        "'Ex de Programmation Conditionnelles.py'", "'booléen.py'",
        'l = [1,2,3,4,5,6,7,8,9].py',
        'create_ui:\n    ui = " | | \\n"\n    print.py',
        "'binairo (2).py'", "'Option RR 29nov.py'",
        'Partie_programmation.py.py', "'Tic tac toe_V2.py'",
        'experimentations_fichiers.py.', "'categories (1).py'",
        "iterables_for.pycompte_car('abracadabra', 'a', 'r')",
        'postfix.lexer.py', "'iterables_for (1).py'",
        "'Programmation3$.py'", 'recette.md', "'TP Fonction.py'",
        "'pour_debogueur (1).py'", "'calcul_interets (2).py'",
        "'Convertion binaire.py'", "'puissance4(1).py'",
        "'booleens (1).py'", "'tictactoe (1) (1).py'", "'tp9 (2).py'",
        "'Exos complémentaires.py'", "'tic_tac_toe (2).py'",
        'ficher_tp11.txt', "'erreurs_cond().py'",
        "'iterable_indexation1 (1) (1).py'", 'md-premier.md',
        "'pour aller plus loin.py'", 'liste.txt', "'TP_booléens.py'",
        "'Projet jeu_2048.py'", 'premier_script.txt',
        "'Projet TIC TAC TOE (1).py'", "'polynôme.py'",
        "'Ex de manipulation Conditionnelles.py'", 'premier_programme.py.',
        "'iterables_for(1).py'", "'puissance4 (1).py'",
        "'Complémentaires.py'", 'fichier.txt', "'TicTacToe_21_11 (2).py'",
        "'tictactoe (2).py'", "'binairo (3).py'", "'fonctions (2).py'",
        "'jeu_421 (1).py'", "'binairo fini.py'", 'manipulations',
        "'TP 2048.py'", "'tic tac toe.py'", "'td sem6.py'",
        'premier_scriptA.txt', "'programme compl.py'",
        "'parcours_interrompu (1) (1).py'",
        "'Instruction Conditionnelle.py'", "'TP2 partiel.py'",
        "'td manipulation.py'", "'td prog fonction.py'",
        "'conditionnelles .py'", "'tdm semaine 9.py'",
        "'conditionnelles(1).py'", 'premier_programme.txt',
        "'fonctions (1).py'", "'td cond.py'", "'tdm semaine 3.py'",
        "'chaine de charactere.py'", "'erreurs tp semaine 3.py'",
        'td02.fonctions.py', "'tdm booleen.py'",
        "'renforce recherche premiere fiche.py'",
        "'semaine 4 partie 2.py'", "'thonny safa.py'",
        "'suplémentaire.py'", "'Complémentaire.py'",
        "'TDM 1 htibault Maton.py'", "'corrigé imbriquée.py'",
        "'puissance4(2).py'", "'TP PROG functions.py'", "'1er exos.py'",
        "'tp semaine 4.py'", "'exercice complementaire iterable.py'",
        "'RR - Séance 3.py'", "'conditionnelles safa.py'",
        "'test td prog.py'", "'CM prog 8.py'",
        "'conditionnelles safa1.py'", "'semaine 7.py'", "'Tic tac toe.py'",
        "'jeu_nim (1).py'", 'toti.txt', "'Tp - Fonction.py'",
        "'tp semaine 3 prog'", "'td semaine 6.py'", "'puissance4 (2).py'",
        "'conditionnelles (1).py'", "'iterables_for (1) (1).py'",
        "'booléen_brouillon.py'", "'nombre binaire.py'", "'Booléen.py'",
        'fichier1.txt', "'test elyes.py'", "'Puissanse 4.py'",
        "'exercice de manipulation  09.py'", 'jeu_421.pyy',
        "'Itérables et boucles for.py'", "'mystere mysterieu.py'",
        "'note UE.py'", '\'Calcul d\'"\'"\'interet.py\'',
        "'renforcé recherche     séance 1.py'", 'fic.txt',
        "'fonctions .py'", "'RR - Séance 4.py'",
        "'exercice complementaire.py'", "'jeu_nim (2).py'",
        "'iterable_indexation (2).py'", "'premier _script.py'",
        'devinette.py3', "'test thonny3.py'", "'booleens(1).py'",
        'explication_commandes.txt', "'booléens2.py'",
        "'le projet de la vie nils py.py'",
        "'td programmation fonction.py'", "'tictactoe 3.py'",
        "'ex complémentaire_1.py'", "'Exercice de programmation.py'",
        "'whilerange (1).py'", "'aller_plus_loin 1.py'", 'pour.deblogueur',
        "'while (1).py'", "'puissance 4 version douae.py'",
        "'Exercice manipulation.py'",
        "'Instruction conditionnelle_brouillon.py'", 'doc.txt',
        "'while (2).py'", "'TD-Exercices-supplémentaires.py'",
        "'tictactoe_jeu_complet (2).py'", "'n° 1.py'",
        "'Exercices_complémentaires.py'",
        "'Devoir Maison 1 programmation.py'",
        "'iterable_indexation(partiel).py'", 'premier.script',
        "'imprimerie def.py'", "'parcours_interrompu (1) (2).py'",
        "'tp fonction.py'", "'brouilloon jeu 421.py'", '.py',
        "'tictactoe(2).py'", "'Exercice complementaires.py'",
        "'tdm1 prog.py'", "'partage bonbon.py'", "'jeu gain.py'",
        "'premier_ script.py'", "'premier_ script.txt'",
        "'iterables_for (2).py'", "'tp 1109.py'", "'erreure alyaising.py'",
        "'binairo (1).py'", 'experimetations.fichiers',
        "'manipulation( pas a rendre).py'", "'tp-prog (à rendre).py'",
        "'conditionnelles (2).py'", 'recette2.md', 'note.UE.py',
        'formule_viau_maton.md', '%Run', "'devoir 1.py'",
        "'Exercices de programmation.py'", "'manipulation (suite).py'",
        "'opérateurs.py'", "'imprimerie (1).py'", 'affichage.py,',
        "'la mer.py'", "'teste binairo.py'", "'manipulations (1).py'",
        "'TP booleen.py'", "'tdm1 exercice de progammation.py'",
        'chaine :.py', "'Jeu tictactoe .py'", "'JEU TICTACTOE FINALE.py'",
        "'fichiers sh .py'", "'débutjeu.py'", "'tictactoe (1) (1) (1).py'",
        "'semaine 6 yasser.py'", 'tictactoe', "'debogueur odi.py'",
        "'premier_programme.py .'",
        "'complementaires_Itérables_et_boucles_for.py'",
        "'the puissance 4 corrected by martin la licorne.py'",
        "'les tours de hanoï.py'", "'Complémentaires_itérables.py'",
        "'UE note.py'", "'while .py'", "'exo_2_executer_le contenu.py'",
        "'manipulations partiel .py'", 'premier_prog.txt',
        "'imprimerie .py'", "'tictactoe .py'",
        "'MANIPULATION BELLOUAR.py'", "'TDM fonction prog.py'",
        "'nteractions_avec_l’utilisateur.py'",
        'fonctions.adnane.el_mazouni.py', "'tdm prog sem 8.py'",
        "'exo de debogueur.py'", "'projet tictatoe.py'", 'fichiers.txt',
        'puissance4.py.py', "'exo date naissance.py'",
        "'TP1 Bis deboggeur.py'", "'exemple_simple (1).py'",
        "'jeu_421 AHMED ET NASSIM FINAL.py'",
        "'Exercices de manipulation.'",
        "'jeu_421 AHMED ET NASSIM FINALFINAL.py'", 'texte.txt',
        "'projet_puissance4 - Copie.py'", 'calculs.interets.py',
        "'tp ahmed.py'", "'prog 6.py'",
        "'Exercices_de_manipulation_Type_booléen.py'",
        '\'exo tp \'"\'"\'\'', "'exo manipulation.py'", "'test tp8.py'",
        "'premier script.py'", "'tdm prog bool.py'"], dtype=object))

There are 236 values not in the exactly pattern (some of them are correct).

In [37]:
# Check empty strings
#pd.set_option('display.max_rows', None) # To show all rows remove the '#'
#pd.set_option('display.max_columns', None) # To show all rows remove the '#'
df.loc[mask,['filename','commandRan','P_codeState']]

,filename,commandRan,P_codeState
832,,%Run -c $EDITOR_CONTENT\n,"# len(""La mer."")\n# max(1, len(""abc""), 123+456..."
833,,%Run -c $EDITOR_CONTENT\n,"# len(""La mer."")\n# max(1, len(""abc""), 123+456..."
1054,,%Run -c $EDITOR_CONTENT\n,NaN
1055,,%Run -c $EDITOR_CONTENT\n,NaN
1056,,%Run -c $EDITOR_CONTENT\n,NaN
...,...,...,...
306902,,%Run -c $EDITOR_CONTENT\n,"prenom = ""Noe""\nlogiciel = ""VSCODE"""
306903,,%Run -c $EDITOR_CONTENT\n,NaN
306904,,%Run -c $EDITOR_CONTENT\n,# Équipe pédagogique de ODI\n# Ce script réali...
306909,,%Run -c $EDITOR_CONTENT\n,# Équipe pédagogique de ODI\n# Ce script réali...
306910,,%Run -c $EDITOR_CONTENT\n,# Équipe pédagogique de ODI\n# Ce script réali...

Empty strings without commandRan or P_codeState

#### 3. Fill empty filename for Run.Debugger

In [38]:
# Before
total       = len(df[df['verb']=='Run.Debugger'])
total_nan   = df[df['verb']=='Run.Debugger']['filename'].isna().sum()
total_empty = (df[df['verb']=='Run.Debugger']['filename'] == '').sum()

print(f"Total rows of Run.Debugger                  : {total}")
print(f"Total rows of Nan in Run.Debugger           : {total_nan}")
print(f"Total rows of empty strings in Run.Debugger : {total_empty}")

Total rows of Run.Debugger                  : 9500
Total rows of Nan in Run.Debugger           : 0
Total rows of empty strings in Run.Debugger : 9500

In [41]:
# Fill by commandRan
mask = df['verb'] == 'Run.Debugger'
df.loc[mask, 'filename'] = data_cleaning.extract_filename_from_commandRan_Run_Debugger(df.loc[mask, 'commandRan'])

In [42]:
# After
total_empty = (df[df['verb']=='Run.Debugger']['filename'] == '').sum()

print(f"Total rows of empty strings in Run.Debugger : {total_empty}")

Total rows of empty strings in Run.Debugger : 0

The number of empty strings reduced from 9500 to zero.

In [ ]:
# Check their value
df[df['verb']=='Run.Debugger']['filename'].unique()

array(['iterable_indexation.py', 'erreurs_boucles_while.py',
       'erreurs_aliasing.py', 'erreurs_boucles_while_suite.py',
       'conditionnels.py', 'erreurs_multiples.py', 'erreurs_cond.py',
       'doctest_parser.py', 'categories.py', 'parcours_interrompu.py',
       'pendu.py', 'fichier.py', 'conditionnelles.py', 'jeu_nim.py',
       'pour_debogueur.py', 'booleens.py', 'while.py', 'iterables_for.py',
       'complementaire.py', 'debogueur-for.py', 'devinette.py', 'prog.py',
       'fonctions.py', 'vzvzfzfzz.py', 'echappement.py',
       'interactions_mystere.py', 'manipulations.py', "'fonctions .py'",
       'calcul_interets.py', 'pour_debogeur.py', 'kk.py',
       'exo_complementaire.py', 'elements_consecutifs.py', 'brouillon.py',
       "'TP booleen.py'", "'premier_programme.py .'",
       "'TP1 Bis deboggeur.py'", "'debogueur TP1 bis 2.py'",
       "'debogueur TP2.py'", 'experimentations_fichiers.py.', 'tp8.py',
       'tp7.py', "'tp9 (2).py'", 'tp4.py', 'tp9.py', 'imbriquees.py',
       'tictactoe.py', 'puissance4.py', 'TP06.py', 'booleen_plusloin.py',
       'manip.py', 'binairo.py', 'jeu_421.py', 'f2_jeux_algo.py',
       'echauffement.py', 'tp_fonctions.py', 'Conditionelle_prog.py',
       'booleens_manipulation.py', 'aller_plus_loin.py',
       'fonctions_manipulatiuons.py', 'manipulation.py',
       'activite_range.py', 'exercicemanipulation.py',
       'exercicedeprog.py', 'saisies_diverses.py', 'saison.py',
       'affichage.py', "'td sem6.py'", 'iterables_for_brouillon.py',
       'Tp8_brouillon.py', 'z.py', 'tests.py', "'debogueur odi.py'",
       'a.py', 'imprimerie.py', "'tictactoe (1).py'",
       'tp_iterables-indexation.py', "'parcours_interrompu (1).py'",
       'pour.deblogueur', 'Jeu_puissance_4.py', 'mesure.py',
       'manipulations_cTPi.py', 'erreurs.py', 'premier_tp.py',
       'experimentations_fichiers.py', 'iterable_indexation_salle_tp.py',
       'debog.py', 'fichiers.py', "'while (1).py'", 'mesure_global.py',
       'premier_script.py', 'jeu_2048.py', 'script.py', 'test.py',
       'RR1.py', 'hexa.py', "'Option RR 1.py'", 'ghjkl.py',
       "'binairo (3).py'", 'calcul_UE.py', "'binairo fini.py'",
       'estimer_py_avec_la_pluie.py', 'noolean.py',
       'erreur_boucle_while.py', 'debogueur_for.py', 'debogueur.py',
       "'puissance 4.py'", "'Exercices_de_manipulation_Type_booléen.py'",
       'tp1.py', 'erreur.py', 'exo_manipulation.py',
       "'TP 11 fichiers.py'",
       'tp_revisions_sur_outil_thonny_et_python.py',
       'TP_aliasing_exercice_de_manipulation.py', "'booleens (1).py'",
       'premier_programme.py', "'iterable_indexation (1).py'", 'exo.py',
       "'puissance 4 version douae.py'", 'TD_2.py', 'exos_bool.py',
       "'chaine de charactere.py'", 'Seance-4-jeux_algorithmiques.py',
       'configurations_init_jeu_vie.py', 'somme_nombres.py',
       'pour_aller_plus_loin.py', 'projet_2048.py',
       "'TD-Exercices-supplémentaires.py'", 'Seance1-2.py', 'debug.py',
       "'exercice complementaire iterable.py'", "'jeu gain.py'",
       'Readme.py', 'miniprojet.py', 's.py', 'h.py', 'p4.py', '2048.py',
       'deuxieme_f.py', 'demin.py', 'Exo1.py', 'Exo2.py', 'v.py', 'f.py',
       'TD9.py', "'corrigé imbriquée.py'", 'revision.py', 'demo_CM7.py',
       'exxx.py', "'manipulations (1).py'", 'fwz.py',
       "'puissance4 (1).py'", 'TD_1.py', 'jeu_nim2.py', 'TD_3.py',
       'Renforce_recherche_Feuille2.py', 'TP_fonctions_N1.py',
       "'premier_ script.py'", 'erreur_boucles_while.py',
       'iterable_for.py', 'erreur_boucles_while_suite.py',
       "'Ex de manipulation Conditionnelles.py'", 'bool.py',
       "'jeu_nim (2).py'", "'Exercice manipulation.py'",
       "'Exercice de programmation.py'",
       "'Exercices de programmation.py'",
       'Exercices_de_manipulation_debogeur.py', 'tictactoe2.py',
       'exo_progTP4.py', 'manipulation_tp7.py', 'devinettes.py',
       "'polynôme.py'", 'manipulationTP4.py', 'manipulationTP3.py',
       'erreur_multiples.py', 'calculs.interets.py',
       "'exo de debogueur.py'", 'exercices_complementaires.py',
       'exercices_complementaires_fonction.py', 'age.py', 'tp_3.py',
       'programation1.py', 'tdm4.py', 'controleTP1.py',
       'iterable_indexation_essaie.py', "'parcours_interrompu (3).py'",
       'TDM08.py', 'TD_debogueur.py', 'erreurs_cTPi.py', 'note_UE.py',
       "'prog 6.py'", 'exo1.py', 'echauf.py', 'tic_tac_toe.py',
       'pour_aller_plus_loin_boucle.py', 'ProjetTICTACTOE.py',
       'ProjetPuissance4.py', 'morpion.py', 'premier_script.txt',
       'while2.py', 'tp09.py', 'iterable_indexation_refaire.py',
       'iterable.py', "'conditionnelles(1).py'", 'tecto.py', 'asup.py',
       'polynomes.py', 'd.py', "'exo de manipulation6.py'",
       "'iterable_indexation (3) (2).py'", 'jeu_tic_tac_toe.py',
       "'jeu tic tac toe.py'", 'TDM1.py', "'Complémentaires.py'",
       'puissance_4.py', 'programmation.py', 'Programmation.py',
       'puissance4_maton_viau.py', 'parcours_interrompu_maton_viau.py',
       'debogueur-for_maton_viau.py',
       'erreurs_boucles_while_maton_viau.py', "'fichiersss (1).py'",
       'tp3-programmation.py', "'test tp8.py'", "'pour_debogueur (1).py'",
       'Condition.py', "'Instruction Conditionnelle.py'", 'affichage.py,',
       'premierscript.py', "'TIC-Tac TP bonus.py'", "'Booléen.py'",
       'TDM8.py', 'Puissance4.py', 'TDM9.py', 'TDM6.py', 'TDM4.py',
       'TDM7.py', 'algo.py', "'RR - Séance 4.py'",
       "'renforcé recherche     séance 1.py'", "'conditionnelles (2).py'",
       'zzzz.py', 'eee.py', 'TD.py', 'TD6.py', 'TP7.py', 'parcours.py',
       "'tdm prog bool.py'", 'S1.py', 'sm9tst.py', 'main3.py',
       "'binairo (1).py'", 'TP1.py', 'savepourdebogguer.py',
       'fonctions2.py', 'postfix_lexer.py', 'TP_booleen.py',
       "'fonctions (2).py'", 'PuissanceWithoutClass.py',
       'prog_tp_fonction_2.py', "'RR 22_11.py'", 'RR.py', 'ii.py', 't.py',
       "'puissance4(2).py'", 'borrar.py', 'fonction_mystere.py',
       'TP4_LOCKB_HEBELAMOU.py', 'debogeur.py', 'gradient.py',
       'projetTicTacToe.py', 'fonction2.py', 'Tic_tac_toe.py',
       'romanemercote.py', 'tdm2.py', 'tdm3.py', 'main.py',
       'complaimentaires.py', 'bandit_monchot.py', 'pour_aller_loin.py',
       'exo_complementaires.py', 'jeu_2048_Muhamad_Sadia.py',
       'premier_scripte.py', 'PROJET.py', 'exercice.py',
       'parcours_interrompu1.py', 'tictactoev2.py',
       'parcours_interrompu2.py', 'debougeur.py', 'iterables_boucles.py',
       'liste.txt', 'huy.py', 'manipulations', 'iterable_indexation-3.py',
       'tictactoe-2-2.py', "'manipulation(3).py'",
       'tictactoe_maton_viau.py', 'TP_calcul_d_interet.py',
       "'Tic tac toe_V2.py'", 'td01.py', 'debugger.py', 'RR_2.py',
       'fontaine_magique.py', 'RR_1.py', 'RR_nb_triang.py',
       'tpfichier.py', 'puissancepc.py', 'config.py', 'tectonic.py',
       'tic-tac-toe.py', "'semaine 6 yasser.py'",
       "'Exercices_de_programmation_Instruction conditionnelle.py'",
       'manipulation_tp07.py', 'exercices_de_prog.py',
       'exos_manipulation_tp6.py', 'prog_tp6.py',
       "'exo_2_executer_le contenu.py'",
       'Exercices_de_manipulation_TDM4.py',
       'exercices_de_proggramation.py', "'itérables.py'", 'RR2.py',
       'RR3.py'], dtype=object)

In [45]:
# Test for values with different pattern in filename of Run.Debugger
pattern = re.compile(r'^[\w\-]+\.py$') # Pattern : name(any number or space).py

filenames       = df[df['verb']=='Run.Debugger']['filename']
invalid_indices = filenames[~filenames.apply(lambda val: isinstance(val, str) and bool(pattern.fullmatch(val.strip())))].index # Extract invalid index

print(f"Total rows    : {len(df[df['verb']=='Run.Debugger']['filename'])}")
print(f"Invalid rows  : {len(invalid_indices)}")

Total rows    : 9500
Invalid rows  : 402

In [46]:
unique_invalid_value = df.loc[list(invalid_indices)]['filename'].unique()
len(unique_invalid_value), unique_invalid_value

(70,
 array(["'fonctions .py'", "'TP booleen.py'", "'premier_programme.py .'",
        "'TP1 Bis deboggeur.py'", "'debogueur TP1 bis 2.py'",
        "'debogueur TP2.py'", 'experimentations_fichiers.py.',
        "'tp9 (2).py'", "'td sem6.py'", "'debogueur odi.py'",
        "'tictactoe (1).py'", "'parcours_interrompu (1).py'",
        'pour.deblogueur', "'while (1).py'", "'Option RR 1.py'",
        "'binairo (3).py'", "'binairo fini.py'", "'puissance 4.py'",
        "'Exercices_de_manipulation_Type_booléen.py'",
        "'TP 11 fichiers.py'", "'booleens (1).py'",
        "'iterable_indexation (1).py'", "'puissance 4 version douae.py'",
        "'chaine de charactere.py'", "'TD-Exercices-supplémentaires.py'",
        "'exercice complementaire iterable.py'", "'jeu gain.py'",
        "'corrigé imbriquée.py'", "'manipulations (1).py'",
        "'puissance4 (1).py'", "'premier_ script.py'",
        "'Ex de manipulation Conditionnelles.py'", "'jeu_nim (2).py'",
        "'Exercice manipulation.py'", "'Exercice de programmation.py'",
        "'Exercices de programmation.py'", "'polynôme.py'",
        'calculs.interets.py', "'exo de debogueur.py'",
        "'parcours_interrompu (3).py'", "'prog 6.py'",
        'premier_script.txt', "'conditionnelles(1).py'",
        "'exo de manipulation6.py'", "'iterable_indexation (3) (2).py'",
        "'jeu tic tac toe.py'", "'Complémentaires.py'",
        "'fichiersss (1).py'", "'test tp8.py'", "'pour_debogueur (1).py'",
        "'Instruction Conditionnelle.py'", 'affichage.py,',
        "'TIC-Tac TP bonus.py'", "'Booléen.py'", "'RR - Séance 4.py'",
        "'renforcé recherche     séance 1.py'", "'conditionnelles (2).py'",
        "'tdm prog bool.py'", "'binairo (1).py'", "'fonctions (2).py'",
        "'RR 22_11.py'", "'puissance4(2).py'", 'liste.txt',
        'manipulations', "'manipulation(3).py'", "'Tic tac toe_V2.py'",
        "'semaine 6 yasser.py'",
        "'Exercices_de_programmation_Instruction conditionnelle.py'",
        "'exo_2_executer_le contenu.py'", "'itérables.py'"], dtype=object))

There is no empty string, and from 402, there are actually 70 values (remove the redundents), they are in the format name.py but they are maybe correct.

In [50]:
# Until now how many filename left
total       = len(df)
total_nan   = df['filename'].isna().sum()
total_empty = (df['filename'] == '').sum()

print(f"Total rows of df                        : {total}")
print(f"Total rows of Nan in filename           : {total_nan}")
print(f"Total rows of empty strings in filename : {total_empty}")

total_empty = (df['filename'] == '').sum()
total_empty

Total rows of df                        : 306914
Total rows of Nan in filename           : 0
Total rows of empty strings in filename : 91954

91954

## Anonymize Data

In [39]:
#anonymized_df = df[['actor', 'binom']].copy() 
#anonymized_df['anonymized_actor'] = df.apply(data_anonymization.anonymize_actor, axis=1)

Replace column actor and binom by anonymized_actor

In [40]:
#df[['actor', 'binom']] = df.apply(data_anonymization.anonymize_actor)


# TODO
- Finish filename cleaning
- Decide what to do with empty strings of Run.Program
- Calculate the total name of student (after cleaning process)
- init_data.py (look at it and the readme of Thomas)
- Anonymization : actor, binom, P-code state, F-code state, columns_with_path
- Process raw data
- Add column that trace the output ?? I don't remember
- Look at notebooknettoyage of Thomas to add a column
- Correct Readme