## Main function has the entire process of 
- Reading
- data_cleaning
- Anonymazing

### Library

In [ ]:
import sys
sys.path.append('../') # these two lines allow the notebook to find the path to the source code contained in 'src'
import pandas as pd
import io_utils, data_cleaning, data_anonymization
from tests import test_preprocessing, test_anonymization
from src_thomas.data.constants import INTERIM_DATA_DIR

### Reading dataframe
Use functions in file **io_utils.py.py**

In [ ]:
df = io_utils.reading_dataframe(dir= INTERIM_DATA_DIR, file_name='traces250102_clean.csv')

The file traces250102_clean.csv exists in the directory.

In [3]:
df[['session.id', 'timestamp.$date', 'time_delta', 'session.duration']]

,session.id,timestamp.$date,time_delta,session.duration
0,139682817762848,2024-12-12 09:53:24.624000+00:00,7 days 00:05:05.313000,NaN
1,139682817762848,2024-12-12 09:53:25.008000+00:00,0 days 00:00:00.384000,NaN
2,139682817762848,2024-12-12 09:54:38.793000+00:00,0 days 00:01:13.785000,0 days 00:01:14.169000
3,139779362711072,2024-10-25 10:19:54.344000+00:00,1 days 00:21:30.977000,NaN
4,139779362711072,2024-10-25 10:19:54.583000+00:00,0 days 00:00:00.239000,NaN
...,...,...,...,...
306941,139911616626448,2024-09-04 14:16:21.990000+00:00,0 days 00:00:53.790000,NaN
306942,139911616626448,2024-09-04 14:18:08.724000+00:00,0 days 00:01:46.734000,NaN
306943,139911616626448,2024-09-04 14:18:08.725000+00:00,0 days 00:00:00.001000,0 days 00:22:32.511000
306944,140578214641424,2024-09-04 13:29:54.300000+00:00,0 days 00:00:00,NaN
306945,140578214641424,2024-09-04 13:33:55.593000+00:00,0 days 00:04:01.293000,0 days 00:04:01.293000

### Print 5 rows and columns of dataframe

In [ ]:
io_utils.column_and_head(df)

5 rows of the dataframe:

   research_usage  result                  _id.$oid  \
0             1.0     NaN  675aa485a7dff6d2d4811b45
1             1.0     NaN  675aa4cea7dff6d2d4811b4f
2             1.0     NaN  675aa4cea7dff6d2d4811b50
3             1.0     NaN  671b54aabd5a98b8f9dc8c14
4             1.0     NaN  671b54f6bd5a98b8f9dc8c45

                    timestamp.$date              stored.$date  \
0  2024-12-12 09:53:24.624000+00:00  2024-11-27T10:57:29.801Z
1  2024-12-12 09:53:25.008000+00:00  2024-11-27T10:57:29.801Z
2  2024-12-12 09:54:38.793000+00:00  2024-11-27T10:57:29.801Z
3  2024-10-25 10:19:54.344000+00:00  2024-08-29T07:34:11.687Z
4  2024-10-25 10:19:54.583000+00:00  2024-08-29T07:34:11.687Z

             actor actor.objectType           verb  \
0  abaly.oura.etu/            Agent  Session.Start
1  abaly.oura.etu/            Agent      File.Open
2  abaly.oura.etu/            Agent    Session.End
3  abaly.oura.etu/            Agent  Session.Start
4  abaly.oura.etu/            Agent      File.Open

                                              object object.objectType  ...  \
0  https://www.cristal.univ-lille.fr/objects/Session          Activity  ...
1     https://www.cristal.univ-lille.fr/objects/File          Activity  ...
2  https://www.cristal.univ-lille.fr/objects/Session          Activity  ...
3  https://www.cristal.univ-lille.fr/objects/Session          Activity  ...
4     https://www.cristal.univ-lille.fr/objects/File          Activity  ...

   P_codeState                                         filename  \
0          NaN                                              NaN
1          NaN  /home/l1/abaly.oura.etu/Downloads/puissance4.py
2          NaN                                              NaN
3          NaN                                              NaN
4          NaN       /home/l1/abaly.oura.etu/TDM 8/devinette.py

                                         F_codeState  Debug_TimeStampEnd  \
0                                                NaN                 NaN
1  # Compléter ici (noms, groupe, contenu fichier...                 NaN
2                                                NaN                 NaN
3                                                NaN                 NaN
4  # L1 MI S1 - Prog\n# TP exos de manipulation -...                 NaN

  Debug_TimeStampActions tests function              time_delta  \
0                    NaN   NaN      NaN  7 days 00:05:05.313000
1                    NaN   NaN      NaN  0 days 00:00:00.384000
2                    NaN   NaN      NaN  0 days 00:01:13.785000
3                    NaN   NaN      NaN  1 days 00:21:30.977000
4                    NaN   NaN      NaN  0 days 00:00:00.239000

         session.duration     seance
0                     NaN        CTP
1                     NaN        CTP
2  0 days 00:01:14.169000        CTP
3                     NaN  semaine_8
4                     NaN  semaine_8

[5 rows x 27 columns]


Columns of the dataframe:

Index(['research_usage', 'result', '_id.$oid', 'timestamp.$date',
       'stored.$date', 'actor', 'actor.objectType', 'verb', 'object',
       'object.objectType', 'object.extension', 'session.id', 'commandRan',
       'result.success', 'stdin', 'stdout', 'stderr', 'P_codeState',
       'filename', 'F_codeState', 'Debug_TimeStampEnd',
       'Debug_TimeStampActions', 'tests', 'function', 'time_delta',
       'session.duration', 'seance'],
      dtype='object')

In [4]:
df['actor'].unique()

# Examples of not matching : 'abaly.oura.etu@univ-lille.fr/' , 'ibrahima.diallo8.etu@/', 'nebut/', 'kilian.graye.etu/luc', 'kade-bhoye.wann.etu/MI1304', 'kade-bhoye.wann.etu/MI1301'

array(['abaly.oura.etu/', 'abaly.oura.etu@univ-lille.fr/',
       'abdallah.saint-ghislain.etu/', 'abdelrahmane.bendjeladjel.etu/',
       'abderrahmen.ayadi.etu/',
       'abderrahmen.ayadi.etu/abderrahmen.ayadi.etu',
       'abderrahmen.ayadi.etu/hazem.hlioui.etu', 'abdoulaye.mbaye.etu/',
       'abdoulaye.nguere.etu/', 'abdoulaye.nguere.etu/serigne.cisse.etu',
       'adam.chikh-touami.etu/', 'adam.chikh-touami.etu/ilian.briki.etu',
       'adam.oukzedou.etu/', 'adam.sialiti.etu/',
       'adama-eliya.avlah.etu/',
       'adama-eliya.avlah.etu/edohson-arnaud.guedou.etu',
       'adame.chairi.etu/', 'adem.kaloun.etu/',
       'adem.kaloun.etu/yasser.jad.etu', 'adnane.el-mazouni.etu/',
       'adnane.el-mazouni.etu/nils.charfeddine-barbier.etu',
       'adrien.vetter.etu/', 'ahmed.bouziani.etu/',
       'ahmed.bouziani.etu/nassim.belouar.etu',
       'ahmed.terfas.etu/rayane.denni.etu',
       'ahmedzeidane.mohamedelmoctar.etu/', 'aissatou-bobo.diallo.etu/',
       'aissatou-bobo.diallo.etu/aissatou-bobo.diallo.etu',
       'aissatou-bobo.diallo.etu/fadil.sani-labo.etu',
       'alban.gahide-fournier.etu/',
       'alban.gahide-fournier.etu/anas.rsmouki.etu', 'alicia.zouadi.etu/',
       'alix.carton2.etu/', 'alix.carton2.etu/romann.szczepaniak.etu',
       'alpha-abdoulaye.diallo.etu/', 'alpha-mahmoudou.diallo.etu/',
       'alpha-mahmoudou.diallo.etu/mamadou-bachir.barry.etu',
       'alpha-mahmoudou.diallo.etu@univ-lille.fr/',
       'amadou-madani.balde.etu/',
       'amadou-madani.balde.etu@univ-lille.fr/', 'amadou.balde.etu/',
       'amel.hadjloum.etu/', 'amine.khadri.etu/',
       'anaba.hilary-williams.etu/', 'anaelle.brient.etu/',
       'anaelle.case.etu/', 'anais.bilek.etu/',
       'anais.bilek.etu/sadia.muhammad.etu', 'anas.bouchlaghem.etu/',
       'anas.bouchlaghem.etu/hajar.amnay.etu',
       'anas.bouchlaghem.etu/nayssam.benessalah.etu', 'anas.en-nor.etu/',
       'anas.en-nor.etu/ismail.nejjar.etu',
       'anas.en-nor.etu/yasser.jad.etu', 'anas.rsmouki.etu/',
       'anass.saidi.etu/', 'anass.saidi.etu@univ-lille.fr/',
       'anass.saidi.etu@univ-lille.fr/bilel.doggui.etu', 'andy.ba.etu/',
       'andy.ba.etu/alpha-abdoulaye.diallo.etu',
       'andy.ba.etu/thierno-abdoulaye.diallo2.etu',
       'andy.ba.etu@univ-lille.fr/amine.khadri.etu', 'ania.belaida.etu/',
       'anis.bitari.etu/', 'anis.medani.etu/',
       'anis.medani.etu/ghizlane.aissaoui.etu',
       'anis.younes.etu@univ-lille.fr/', 'antoine.bollen.etu/',
       'antoine.bollen.etu/avsin.ata.etu',
       'antoine.bollen.etu/julien.buseyne.etu', 'antoine.hotin.etu/',
       'antoine.hotin.etu/igor.belyaev.etu', 'antoine.lherbier.etu/',
       'antoine.vanhauwaert.etu/',
       'antoine.vanhauwaert.etu/elias.debab.etu', 'anton.dablement.etu/',
       'asmaa.saibi.etu/', 'asmaa.saibi.etu/hamza.chebbah.etu',
       'assia.mousselmal.etu/', 'assia.mousselmal.etu/clement.sorge.etu',
       'augustin.derieux.etu/', 'aurelien.bithorel.etu/',
       'aurelien.bithorel.etu@univ-lille.fr/', 'aurelien.dez.etu/',
       'avsin.ata.etu/', 'avsin.ata.etu/antoine.bollen.etu',
       'avsin.ata.etu/pierrick.cardoso.etu', 'axel.flippe.etu/',
       'axel.flippe.etu/mayas.bouhadda.etu', 'aya.rhani.etu/',
       'aya.rhani.etu/safa-khawthar.draouche.etu',
       'ayao-landry-jeremie.dzossou-afanlete.etu/',
       'aymeric.amblanc.etu/', 'aymeric.amblanc.etu/hugo.vandewalle2.etu',
       'ayoub.el-khayari.etu/', 'ayoub.el-khayari.etu/youssef.airaki.etu',
       'ben-magloire.hoessi.etu/', 'bilal.oualbagui.etu/',
       'bilal.ouazize.etu/', 'bilel.doggui.etu/',
       'bilel.doggui.etu/anass.saidi.etu',
       'bilel.doggui.etu/mohammed.abdennour.etu',
       'bilel.doggui.etu/nolan.halluin.etu',
       'bilel.doggui.etu@univ-lille.fr/anass.saidi.etu',
       'bilel.taieb.etu/', 'bilel.taieb.etu/julien.buseyne.etu',
       'bilel.taieb.etu/mervin.kalistas.etu', 'boris.mutagoma.etu/',
       'boris.mutagoma.etu/boris.mutagoma.etu', 'boubacar.barry.etu/',
       'candice.billerait.etu/', 'chaima.chakroun.etu/',
       'chainez.boucherim--catry.etu/', 'claire.tetart.etu/',
       'clara.kombe.etu/', 'clement.sorge.etu/',
       'clement.sorge.etu/asmaa.saibi.etu',
       'clement.sorge.etu/assia.mousselmal.etu',
       'clement.sorge.etu/ibrahima.diallo8.etu', 'dania.baroud.etu/',
       'dania.baroud.etu/imrane.mehenni.etu',
       'dantoire-lalle.namoni.etu/', 'dario.bitri.etu/',
       'dariya.kinadinova.etu/',
       'dariya.kinadinova.etu/imane.messali.etu', 'david.kahak.etu/',
       'demba.diao.etu/', 'demba.diao.etu/keba.thiam.etu',
       'djama.souleiman-abdi.etu/', 'douae.ramdani.etu/',
       'douae.ramdani.etu/elyna.belkacemi.etu',
       'edohson-arnaud.guedou.etu/',
       'edohson-arnaud.guedou.etu/adama-eliya.avlah.etu',
       'edohson-arnaud.guedou.etu/mamadou-sellou.diallo.etu',
       'el-hadji-malick.gueye.etu/', 'elias.debab.etu/',
       'elias.debab.etu/antoine.vanhauwaert.etu', 'elliot.launay.etu/',
       'elliot.leroux.etu/', 'elyas.rabhiu.etu/', 'elyes.guedria.etu/',
       'elyes.guedria.etu/eya.yahyaoui.etu',
       'elyes.guedria.etu/walid.farrash.etu',
       'elyna.belkacemi.etu/douae.ramdani.etu',
       'emeline.jonneaux-pantofel.etu/', 'emma.souvestre.etu/',
       'enrick.debailleul.etu/', 'enrick.debailleul.etu/mehdi.rabi.etu',
       'enrick.debailleul.etu/mohamed-sami.mousaid.etu',
       'enzo.dewez.etu/', 'enzo.dewez.etu/noa.gobaut.etu',
       'enzo.miuzzo.etu/', 'enzo.miuzzo.etu/hugo.deschamps2.etu',
       'ethan.duhot.etu/', 'ethan.duhot.etu/ethan.duhot.etu',
       'ethan.duhot.etu/matthieu.bouin.etu', 'ethan.slowack.etu/',
       'eya.yahyaoui.etu/', 'eya.yahyaoui.etu/elyes.guedria.etu',
       'eya.yahyaoui.etu@univ-lille.fr/eya.yahyaoui.etu',
       'eya.zeidi.etu/', 'fadil.sani-labo.etu/',
       'fadil.sani-labo.etu/aissatou-bobo.diallo.etu',
       'fadila.taffa.etu/', 'farmata-sall.sow.etu/',
       'fatima.almohamed-alsadou.etu/', 'fatoumata-bintou.traore.etu/',
       'fatoumata-bintou.traore.etu/sokhna.dia2.etu',
       'faustine.descatoire.etu/', 'fawaaz.oyedotun.etu/',
       'fawaaz.oyedotun.etu/jacques-lazare.diatta.etu',
       'fayez.ben-bouali.etu/', 'fayez.ben-bouali.etu@univ-lille.fr/',
       'florian.casteur-delpierre.etu/', 'florian.heyte.etu/',
       'florian.heyte.etu/florian.heyte.etu',
       'gabriel.maatouk-dorlot.etu/',
       'gabriel.maatouk-dorlot.etu/elliot.launay.etu',
       'gabriel.maatouk-dorlot.etu/jeremie.dhollande.etu',
       'ghizlane.aissaoui.etu/', 'ghizlane.aissaoui.etu/anis.medani.etu',
       'grace-rochelde.louhanana.etu/', 'guillaume.depelchin.etu/',
       'guillaume.depelchin.etu/sami.mili.etu',
       'hadja-maimouna.balde.etu/', 'hadjara.darou.etu/',
       'hajar.amnay.etu/', 'hajar.amnay.etu/anas.bouchlaghem.etu',
       'hajar.zeaiter.etu/', 'hamza.chebbah.etu/',
       'hamza.chebbah.etu/nadjib.zoubir.etu', 'hazem.hlioui.etu/',
       'hazem.hlioui.etu/abderrahmen.ayadi.etu', 'helio.dequeker.etu/',
       'henry.hebelamou.etu/',
       'henry.hebelamou.etu/pedro-luis.lock-benites.etu',
       'hichame.haddou.etu/', 'hichame.haddou.etu/alicia.zouadi.etu',
       'hichame.haddou.etu/luc.duriez.etu', 'hichem.belabes.etu/',
       'hugo.deschamps2.etu/', 'hugo.deschamps2.etu/enzo.miuzzo.etu',
       'hugo.deschamps2.etu/mehdi.chaib-deraa.etu', 'hugo.leleu.etu/',
       'hugo.vandewalle2.etu/',
       'hugo.vandewalle2.etu/aymeric.amblanc.etu', 'ibn-farrid.sama.etu/',
       'ibrahim.yahia.etu/', 'ibrahim.yahia.etu/mounir.achbad.etu',
       'ibrahima-al-amine.diaw.etu/',
       'ibrahima-al-amine.diaw.etu/abdoulaye.nguere.etu',
       'ibrahima-al-amine.diaw.etu/serigne.cisse.etu',
       'ibrahima.diallo8.etu/', 'ibrahima.diallo8.etu@/',
       'ibrahima.diallo8.etu@univ-lille.fr/', 'ibrahima.diop.etu/',
       'ibrahima.sylla2.etu/', 'igor.belyaev.etu/', 'ilian.briki.etu/',
       'ilian.briki.etu/adam.chikh-touami.etu', 'ilyes.benferhat.etu/',
       'ilyes.benferhat.etu/louis.warembourg.etu',
       'ilyes.benferhat.etu/romain.balitout.etu', 'ilyes.hadadi.etu/',
       'ilyes.hadadi.etu/qassim.kahoul.etu', 'imad.berhoum.etu/',
       'imad.berhoum.etu/mehdi.rabi.etu', 'imane.messali.etu/',
       'imane.messali.etu/dariya.kinadinova.etu',
       'imane.messali.etu/douae.ramdani.etu',
       'imane.messali.etu/elyna.belkacemi.etu', 'imrane.mehenni.etu/',
       'imrane.mehenni.etu/asmaa.saibi.etu',
       'imrane.mehenni.etu/sami.boumiz.etu',
       'imrane.mehenni.etu@univ-lille.fr/',
       'imrane.mehenni.etu@univ-lille.fr/marion.le-guen.etu',
       'ismail.nejjar.etu/', 'ismail.nejjar.etu/said.dahmani.etu',
       'ivan.mbonjo.etu/', 'jacques-lazare.diatta.etu/',
       'jacques-lazare.diatta.etu/fawaaz.oyedotun.etu',
       'jean-mayes.zitouni.etu/', 'jeremie.dhollande.etu/',
       'jeremie.dhollande.etu/enzo.dewez.etu', 'josselin.hebert.etu/',
       'jules.salandre.etu/', 'julien.batrelle.etu/',
       'julien.buseyne.etu/', 'julien.buseyne.etu/antoine.bollen.etu',
       'julien.buseyne.etu/pierrick.cardoso.etu', 'julien.choquet.etu/',
       'julien.choquet.etu/anaba.hilary-williams.etu',
       'julien.deneubourg.etu/',
       'julien.deneubourg.etu/florian.heyte.etu',
       'julien.deneubourg.etu/mehmet.kucukkalfa.etu',
       'kade-bhoye.wann.etu/', 'kade-bhoye.wann.etu/MI1301',
       'kade-bhoye.wann.etu/MI1304', 'kamal-deen-oloumide.savi.etu/',
       'kamal-deen-oloumide.savi.etu/dantoire-lalle.namoni.etu',
       'keba.thiam.etu/', 'kellian.sory.etu/',
       'kellian.sory.etu/asmaa.saibi.etu', 'khadim.beye.etu/',
       'kilian.graye.etu/', 'kilian.graye.etu/luc',
       'kilian.graye.etu/luc.duriez.etu', 'koffi-john.evon.etu/',
       'koffi-john.evon.etu/yves.djegnon.etu', 'koffi.gantchou.etu/',
       'koffi.gantchou.etu/gora.diop.etu',
       'koffi.gantchou.etu/kotchi-ange-gedeon.kama.etu',
       'komi.dogbe.etu/', 'komivi.akpata.etu/',
       'komivi.akpata.etu/dantoire-lalle.namoni.etu',
       'komivi.akpata.etu/koffi.gantchou.etu',
       'kotchi-ange-gedeon.kama.etu/', 'lansana.beavogui.etu/',
       'lansana.beavogui.etu/jacques-lazare.diatta.etu',
       'lea.claire.etu/', 'lea.vannobel.etu/',
       'lea.vannobel.etu/samuel.huret.etu', 'lino.mallevaey.etu/',
       'lino.mallevaey.etu/sadia.muhammad.etu',
       'lino.mallevaey.etu/yanis.brahimi.etu', 'louane.deligny.etu/',
       'louane.deligny.etu/amel.hadjloum.etu', 'loucas.meganck.etu/',
       'louis.warembourg.etu/',
       'louis.warembourg.etu/thomas.desbuissons.etu', 'luc.duriez.etu/',
       'luc.duriez.etu/kilian.graye.etu', 'lucile.viau.etu/',
       'lucile.viau.etu/thibault.maton.etu', 'lyna.boussahela.etu/',
       'm-bah-ange-pascal.tanoh.etu/',
       'm-bah-ange-pascal.tanoh.etu/manel.kracheni.etu',
       'm-bah-ange-pascal.tanoh.etu@univ-lille.fr/',
       'maeva.coppey.etu/hajar.amnay.etu',
       'maeva.coppey.etu/nayssam.benessalah.etu', 'maeva.ochsenfeld.etu/',
       'magatte.mbathie.etu/', 'malak.boudoh-mimun.etu/',
       'malak.boudoh-mimun.etu/shirel.da-silva.etu',
       'malick-ndiaye.kone.etu/', 'mamadou-alpha.diallo2.etu/',
       'mamadou-bachir.barry.etu/', 'mamadou-sellou.diallo.etu/',
       'mamadou-sellou.diallo.etu/mervin.kalistas.etu',
       'mamadou.barry8.etu/', 'mamadou.diallo9.etu/',
       'mamadou.diallo9.etu/mamadou.diallo9.etu', 'mamadou.manga.etu/',
       'mame-diarra.tall.etu/', 'mame-ngor.aw.etu/', 'manel.cherief.etu/',
       'manel.cherief.etu/hajar.amnay.etu',
       'manel.cherief.etu/serigne.cisse.etu', 'manel.kracheni.etu/',
       'manel.kracheni.etu/douae.ramdani.etu',
       'manel.kracheni.etu/fawaaz.oyedotun.etu',
       'manel.kracheni.etu/m-bah-ange-pascal.tanoh.etu',
       'maodo.niang.etu/', 'marcio.vieira-matos.etu/',
       'marion.le-guen.etu/', 'marion.le-guen.etu/imrane.mehenni.etu',
       'marion.le-guen.etu/walid.farrash.etu',
       'marion.le-guen.etu@univ-lille.fr/', 'marko.yanovskyi.etu/',
       'maryam.hezzat.etu/', 'massama.keita.etu/', 'massil.kichi.etu/',
       'matheo.facon.etu/', 'matheo.paszkowski.etu/',
       'mathis.thomas.etu/', 'mathis.thomas.etu/paul.heroguel.etu',
       'matthieu.bouin.etu/', 'matthieu.misiak.etu/',
       'matthieu.misiak.etu/loucas.meganck.etu', 'maxence.magras.etu/',
       'maxime.mpungwe.etu/', 'maxime.mpungwe.etu/ahmed.terfas.etu',
       'mayas.bouhadda.etu/', 'mehdi.chaib-deraa.etu/', 'mehdi.rabi.etu/',
       'mehdi.rabi.etu/imad.berhoum.etu', 'mehdi.rabi.etu/mehdi.rabi.etu',
       'mehmet.kucukkalfa.etu/', 'mervin.kalistas.etu/',
       'mervin.kalistas.etu/mamadou-sellou.diallo.etu',
       'merwan.sergent.etu/', 'michael.tankeu-bigna.etu/',
       'milan.caillot.etu/', 'mirdaas-alfa-kaza.alidou.etu/',
       'mohamed-el-amine.samahri.etu/',
       'mohamed-el-amine.samahri.etu@univ-lille.fr/',
       'mohamed-nazim.ait-kaci.etu/', 'mohamed-sami.mousaid.etu/',
       'mohamed-sami.mousaid.etu/enrick.debailleul.etu',
       'mohamed.belfadel.etu/', 'mohamed.belfadel.etu/rayane.asma.etu',
       'mohamed.djafer.etu/', 'mohamed.mana.etu/',
       'mohamed.mana.etu/naim.abdellaoui.etu',
       'mohamed.mana.etu/samuel.scavone.etu',
       'mohamed.mana.etu/tarik.amirat.etu', 'mohamed.trougouty.etu/',
       'mohamed.zemmouri.etu/', 'mohammed.abdennour.etu/',
       'mohammed.abdennour.etu/bilel.doggui.etu', 'momar.niang.etu/',
       'momar.niang.etu/mamadou.manga.etu', 'mounir.achbad.etu/',
       'mounir.achbad.etu/ibrahim.yahia.etu', 'mounir.zebboudji.etu/',
       'mugisha.nzakamwita.etu/',
       'mugisha.nzakamwita.etu/alpha-abdoulaye.diallo.etu',
       'mugisha.nzakamwita.etu@univ-lille.fr/', 'nadjib.zoubir.etu/',
       'naim.abdellaoui.etu/', 'naim.abdellaoui.etu/mohamed.mana.etu',
       'nassim.abbad.etu/', 'nassim.abbad.etu/nassim.abbad.etu',
       'nassim.arbaoui.etu/', 'nassim.arbaoui.etu/willy.nguyen.etu',
       'nassim.belouar.etu/', 'nassim.belouar.etu/ahmed.bouziani.etu',
       'nassim.belouar.etu/alicia.zouadi.etu',
       'nassim.belouar.etu@univ-lille.fr/', 'nathan.remoleux.etu/',
       'nayad.senaici.etu/', 'nayssam.benessalah.etu/',
       'nayssam.benessalah.etu/anas.bouchlaghem.etu', 'ndongo.diao.etu/',
       'nebut/', 'nhungocanh.nguyen.etu/', 'nicolas.raharinaivo.etu/',
       'nicolas.raharinaivo.etu/noa.gobaut.etu',
       'nils.charfeddine-barbier.etu/',
       'nils.charfeddine-barbier.etu/florian.casteur-delpierre.etu',
       'noa.gobaut.etu/', 'noa.gobaut.etu@univ-lille.fr/',
       'noam.taibi.etu/', 'noam.taibi.etu/yanko.lemoine.etu',
       'noe.carpentier.etu/', 'noe.le-van-canh-dit-ban.etu/',
       'nolan.chevalier.etu/', 'nolan.halluin.etu/',
       'nolan.halluin.etu/abdallah.saint-ghislain.etu',
       'nourou.diouf.etu/', 'oscar.abidi.etu/', 'oumou.diallo3.etu/',
       'oyawa.liza.etu/', 'pap-amath.thiam.etu/', 'paul.heroguel.etu/',
       'paul.heroguel.etu/josselin.hebert.etu',
       'pedro-luis.lock-benites.etu/',
       'pedro-luis.lock-benites.etu/henry.hebelamou.etu',
       'pedro-luis.lock-benites.etu/shema.mugambira.etu',
       'pierre.delecourt.etu/', 'pierrick.cardoso.etu/',
       'pierrick.cardoso.etu/avsin.ata.etu', 'qassim.kahoul.etu/',
       'qassim.kahoul.etu/ilyes.hadadi.etu',
       'qassim.kahoul.etu/mehdi.rabi.etu', 'raphael.crozat-moreau.etu/',
       'raphael.tafani.etu/', 'rayan.fortas.etu/', 'rayane.asma.etu/',
       'rayane.denni.etu/', 'rayane.denni.etu/adame.chairi.etu',
       'rayane.denni.etu/ahmed.terfas.etu', 'richard.kpande-adzare.etu/',
       'richard.kpande-adzare.etu/oumou.diallo3.etu',
       'romain.balitout.etu/', 'romain.balitout.etu/ilyes.benferhat.etu',
       'romain.faidherbe.etu/', 'romain.faidherbe.etu/salim.rachdi.etu',
       'romain.ruelle.etu/', 'romane.deleau.etu/',
       'romane.deleau.etu/imrane.mehenni.etu',
       'romane.deleau.etu/marion.le-guen.etu',
       'romane.deleau.etu/sami.boumiz.etu', 'romann.szczepaniak.etu/',
       'romann.szczepaniak.etu/alix.carton2.etu',
       'rosche-rostell.batchi-vouala.etu/', 'rose.pananceau.etu/',
       'rose.pananceau.etu/pap-amath.thiam.etu', 'ruben.cassin.etu/',
       'sabine.boukais.etu/', 'sadia.muhammad.etu/',
       'safa-khawthar.draouche.etu/',
       'safa-khawthar.draouche.etu/aya.rhani.etu', 'said.dahmani.etu/',
       'said.dahmani.etu/ismail.nejjar.etu',
       'said.dahmani.etu/said.dahmani.etu', 'salem.el-bouhouti.etu/',
       'salem.el-bouhouti.etu/mohamed-el-amine.samahri.etu',
       'salim.rachdi.etu/', 'sami.boumiz.etu/',
       'sami.boumiz.etu/hamza.chebbah.etu', 'sami.mili.etu/',
       'sami.mili.etu/sami.mili.etu', 'samir.fandi.etu/',
       'samir.fandi.etu@univ-lille.fr/', 'samuel.huret.etu/',
       'samuel.huret.etu/faustine.descatoire.etu',
       'samuel.huret.etu/lea.vannobel.etu', 'samuel.scavone.etu/',
       'samuel.scavone.etu/hichame.haddou.etu',
       'samuel.scavone.etu/yastene.chemam.etu', 'samy.yahia-cherif.etu/',
       'samy.yahia-cherif.etu/samy.yahia-cherif.etu',
       'samy.yahia-cherif.etu/yanis.nabet.etu', 'serhii.ivkin.etu/',
       'serigne.cisse.etu/', 'serigne.cisse.etu/abdoulaye.nguere.etu',
       'serigne.cisse.etu/manel.cherief.etu',
       'serigne.cisse.etu/rayane.denni.etu',
       'shadrak-arthur.banouanina.etu/',
       'shadrak-arthur.banouanina.etu/komivi.akpata.etu',
       'shema.mugambira.etu/', 'shirel.da-silva.etu/',
       'shirel.da-silva.etu/malak.boudoh-mimun.etu',
       'shirel.da-silva.etu/maodo.niang.etu', 'sokhna.dia2.etu/',
       'sokhna.dia2.etu/fatoumata-bintou.traore.etu',
       'sokhna.dia2.etu/hadjara.darou.etu', 'taissir.el-hammouchi.etu/',
       'tarik.amirat.etu/', 'thibault.maton.etu/',
       'thibault.maton.etu/lucile.viau.etu',
       'thierno-abdoulaye.diallo2.etu/',
       'thierno-abdoulaye.diallo2.etu/andy.ba.etu', 'thierno.barry4.etu/',
       'thomas.desbuissons.etu/',
       'thomas.desbuissons.etu/ahmed.bouziani.etu',
       'thomas.desbuissons.etu/louis.warembourg.etu',
       'timothe.devigne.etu/', 'tristan.melchior.etu/',
       'valentin.faust.etu/', 'wail.ghouila.etu/', 'walid.farrash.etu/',
       'walid.farrash.etu/asmaa.saibi.etu',
       'walid.farrash.etu/elyes.guedria.etu',
       'walid.farrash.etu/eya.yahyaoui.etu', 'waylan.godfrey.etu/',
       'weeti-sharleen.akogbeto.etu/', 'willy.nguyen.etu/',
       'willy.nguyen.etu/nassim.arbaoui.etu', 'yadiradjen.mounien.etu/',
       'yanis.brahimi.etu/', 'yanis.gannar.etu/',
       'yanis.gannar.etu/david.kahak.etu', 'yanis.kharchi.etu/',
       'yanis.nabet.etu/', 'yanis.nabet.etu/samy.yahia-cherif.etu',
       'yanko.lemoine.etu/', 'yanko.lemoine.etu/noam.taibi.etu',
       'yasser.jad.etu/', 'yastene.chemam.etu/',
       'yastene.chemam.etu/alicia.zouadi.etu',
       'yastene.chemam.etu/naim.abdellaoui.etu',
       'yastene.chemam.etu/samuel.scavone.etu',
       'yastene.chemam.etu/tarik.amirat.etu',
       'yastene.chemam.etu/yastene.chemam.etu', 'yohan.michel.etu/',
       'youssef.airaki.etu/', 'yves.djegnon.etu/',
       'yves.djegnon.etu/fatoumata-bintou.traore.etu',
       'zacharie.deroo.etu/', 'zacharie.deroo.etu/noe.carpentier.etu'],
      dtype=object)

### Clean dataframe
- Change time format
- Clean actor column

#### Change time format

In [16]:
df[['session.id', 'timestamp.$date', 'time_delta', 'session.duration']]

,session.id,timestamp.$date,time_delta,session.duration
0,139682817762848,2024-12-12 09:53:24.624000+00:00,7 days 00:05:05.313000,NaN
1,139682817762848,2024-12-12 09:53:25.008000+00:00,0 days 00:00:00.384000,NaN
2,139682817762848,2024-12-12 09:54:38.793000+00:00,0 days 00:01:13.785000,0 days 00:01:14.169000
3,139779362711072,2024-10-25 10:19:54.344000+00:00,1 days 00:21:30.977000,NaN
4,139779362711072,2024-10-25 10:19:54.583000+00:00,0 days 00:00:00.239000,NaN
...,...,...,...,...
306941,139911616626448,2024-09-04 14:16:21.990000+00:00,0 days 00:00:53.790000,NaN
306942,139911616626448,2024-09-04 14:18:08.724000+00:00,0 days 00:01:46.734000,NaN
306943,139911616626448,2024-09-04 14:18:08.725000+00:00,0 days 00:00:00.001000,0 days 00:22:32.511000
306944,140578214641424,2024-09-04 13:29:54.300000+00:00,0 days 00:00:00,NaN
306945,140578214641424,2024-09-04 13:33:55.593000+00:00,0 days 00:04:01.293000,0 days 00:04:01.293000

In [ ]:
df = data_cleaning.clean_time(df)

In [6]:
df[['session.id', 'timestamp.$date', 'time_delta', 'session.duration']]

,session.id,timestamp.$date,time_delta,session.duration
0,139682817762848,2024-12-12 09:53:24.624000+00:00,7 days 00:05:05.313000,NaN
1,139682817762848,2024-12-12 09:53:25.008000+00:00,0 days 00:00:00.384000,NaN
2,139682817762848,2024-12-12 09:54:38.793000+00:00,0 days 00:01:13.785000,0 days 00:01:14.169000
3,139779362711072,2024-10-25 10:19:54.344000+00:00,1 days 00:21:30.977000,NaN
4,139779362711072,2024-10-25 10:19:54.583000+00:00,0 days 00:00:00.239000,NaN
...,...,...,...,...
306941,139911616626448,2024-09-04 14:16:21.990000+00:00,0 days 00:00:53.790000,NaN
306942,139911616626448,2024-09-04 14:18:08.724000+00:00,0 days 00:01:46.734000,NaN
306943,139911616626448,2024-09-04 14:18:08.725000+00:00,0 days 00:00:00.001000,0 days 00:22:32.511000
306944,140578214641424,2024-09-04 13:29:54.300000+00:00,0 days 00:00:00,NaN
306945,140578214641424,2024-09-04 13:33:55.593000+00:00,0 days 00:04:01.293000,0 days 00:04:01.293000

#### Clean actor column

In [ ]:
df[['actor', 'binom']] = df['actor'].apply(data_cleaning.clean_actor)

luc
luc
luc
luc
luc
luc
luc
luc
luc
luc
luc
luc
luc
luc
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut
nebut

In [8]:
df[['actor', 'binom']]

                     actor               binom
0           abaly.oura.etu                None
1           abaly.oura.etu                None
2           abaly.oura.etu                None
3           abaly.oura.etu                None
4           abaly.oura.etu                None
...                    ...                 ...
306941  zacharie.deroo.etu  noe.carpentier.etu
306942  zacharie.deroo.etu  noe.carpentier.etu
306943  zacharie.deroo.etu  noe.carpentier.etu
306944  zacharie.deroo.etu  noe.carpentier.etu
306945  zacharie.deroo.etu  noe.carpentier.etu

[306946 rows x 2 columns]

In [9]:
# Examples of not matching : 'abaly.oura.etu@univ-lille.fr/' , 'ibrahima.diallo8.etu@/', 'nebut/', 'kilian.graye.etu/luc', 'kade-bhoye.wann.etu/MI1304', 'kade-bhoye.wann.etu/MI1301'

In [10]:
df['actor'].unique()

array(['abaly.oura.etu', 'abdallah.saint-ghislain.etu',
       'abdelrahmane.bendjeladjel.etu', 'abderrahmen.ayadi.etu',
       'abdoulaye.mbaye.etu', 'abdoulaye.nguere.etu',
       'adam.chikh-touami.etu', 'adam.oukzedou.etu', 'adam.sialiti.etu',
       'adama-eliya.avlah.etu', 'adame.chairi.etu', 'adem.kaloun.etu',
       'adnane.el-mazouni.etu', 'adrien.vetter.etu', 'ahmed.bouziani.etu',
       'ahmed.terfas.etu', 'ahmedzeidane.mohamedelmoctar.etu',
       'aissatou-bobo.diallo.etu', 'alban.gahide-fournier.etu',
       'alicia.zouadi.etu', 'alix.carton2.etu',
       'alpha-abdoulaye.diallo.etu', 'alpha-mahmoudou.diallo.etu',
       'amadou-madani.balde.etu', 'amadou.balde.etu', 'amel.hadjloum.etu',
       'amine.khadri.etu', 'anaba.hilary-williams.etu',
       'anaelle.brient.etu', 'anaelle.case.etu', 'anais.bilek.etu',
       'anas.bouchlaghem.etu', 'anas.en-nor.etu', 'anas.rsmouki.etu',
       'anass.saidi.etu', 'andy.ba.etu', 'ania.belaida.etu',
       'anis.bitari.etu', 'anis.medani.etu', 'anis.younes.etu',
       'antoine.bollen.etu', 'antoine.hotin.etu', 'antoine.lherbier.etu',
       'antoine.vanhauwaert.etu', 'anton.dablement.etu',
       'asmaa.saibi.etu', 'assia.mousselmal.etu', 'augustin.derieux.etu',
       'aurelien.bithorel.etu', 'aurelien.dez.etu', 'avsin.ata.etu',
       'axel.flippe.etu', 'aya.rhani.etu',
       'ayao-landry-jeremie.dzossou-afanlete.etu', 'aymeric.amblanc.etu',
       'ayoub.el-khayari.etu', 'ben-magloire.hoessi.etu',
       'bilal.oualbagui.etu', 'bilal.ouazize.etu', 'bilel.doggui.etu',
       'bilel.taieb.etu', 'boris.mutagoma.etu', 'boubacar.barry.etu',
       'candice.billerait.etu', 'chaima.chakroun.etu',
       'chainez.boucherim--catry.etu', 'claire.tetart.etu',
       'clara.kombe.etu', 'clement.sorge.etu', 'dania.baroud.etu',
       'dantoire-lalle.namoni.etu', 'dario.bitri.etu',
       'dariya.kinadinova.etu', 'david.kahak.etu', 'demba.diao.etu',
       'djama.souleiman-abdi.etu', 'douae.ramdani.etu',
       'edohson-arnaud.guedou.etu', 'el-hadji-malick.gueye.etu',
       'elias.debab.etu', 'elliot.launay.etu', 'elliot.leroux.etu',
       'elyas.rabhiu.etu', 'elyes.guedria.etu', 'elyna.belkacemi.etu',
       'emeline.jonneaux-pantofel.etu', 'emma.souvestre.etu',
       'enrick.debailleul.etu', 'enzo.dewez.etu', 'enzo.miuzzo.etu',
       'ethan.duhot.etu', 'ethan.slowack.etu', 'eya.yahyaoui.etu',
       'eya.zeidi.etu', 'fadil.sani-labo.etu', 'fadila.taffa.etu',
       'farmata-sall.sow.etu', 'fatima.almohamed-alsadou.etu',
       'fatoumata-bintou.traore.etu', 'faustine.descatoire.etu',
       'fawaaz.oyedotun.etu', 'fayez.ben-bouali.etu',
       'florian.casteur-delpierre.etu', 'florian.heyte.etu',
       'gabriel.maatouk-dorlot.etu', 'ghizlane.aissaoui.etu',
       'grace-rochelde.louhanana.etu', 'guillaume.depelchin.etu',
       'hadja-maimouna.balde.etu', 'hadjara.darou.etu', 'hajar.amnay.etu',
       'hajar.zeaiter.etu', 'hamza.chebbah.etu', 'hazem.hlioui.etu',
       'helio.dequeker.etu', 'henry.hebelamou.etu', 'hichame.haddou.etu',
       'hichem.belabes.etu', 'hugo.deschamps2.etu', 'hugo.leleu.etu',
       'hugo.vandewalle2.etu', 'ibn-farrid.sama.etu', 'ibrahim.yahia.etu',
       'ibrahima-al-amine.diaw.etu', 'ibrahima.diallo8.etu',
       'ibrahima.diop.etu', 'ibrahima.sylla2.etu', 'igor.belyaev.etu',
       'ilian.briki.etu', 'ilyes.benferhat.etu', 'ilyes.hadadi.etu',
       'imad.berhoum.etu', 'imane.messali.etu', 'imrane.mehenni.etu',
       'ismail.nejjar.etu', 'ivan.mbonjo.etu',
       'jacques-lazare.diatta.etu', 'jean-mayes.zitouni.etu',
       'jeremie.dhollande.etu', 'josselin.hebert.etu',
       'jules.salandre.etu', 'julien.batrelle.etu', 'julien.buseyne.etu',
       'julien.choquet.etu', 'julien.deneubourg.etu',
       'kade-bhoye.wann.etu', 'kamal-deen-oloumide.savi.etu',
       'keba.thiam.etu', 'kellian.sory.etu', 'khadim.beye.etu',
       'kilian.graye.etu', 'koffi-john.evon.etu', 'koffi.gantchou.etu',
       'komi.dogbe.etu', 'komivi.akpata.etu',
       'kotchi-ange-gedeon.kama.etu', 'lansana.beavogui.etu',
       'lea.claire.etu', 'lea.vannobel.etu', 'lino.mallevaey.etu',
       'louane.deligny.etu', 'loucas.meganck.etu', 'louis.warembourg.etu',
       'luc.duriez.etu', 'lucile.viau.etu', 'lyna.boussahela.etu',
       'm-bah-ange-pascal.tanoh.etu', 'maeva.coppey.etu',
       'maeva.ochsenfeld.etu', 'magatte.mbathie.etu',
       'malak.boudoh-mimun.etu', 'malick-ndiaye.kone.etu',
       'mamadou-alpha.diallo2.etu', 'mamadou-bachir.barry.etu',
       'mamadou-sellou.diallo.etu', 'mamadou.barry8.etu',
       'mamadou.diallo9.etu', 'mamadou.manga.etu', 'mame-diarra.tall.etu',
       'mame-ngor.aw.etu', 'manel.cherief.etu', 'manel.kracheni.etu',
       'maodo.niang.etu', 'marcio.vieira-matos.etu', 'marion.le-guen.etu',
       'marko.yanovskyi.etu', 'maryam.hezzat.etu', 'massama.keita.etu',
       'massil.kichi.etu', 'matheo.facon.etu', 'matheo.paszkowski.etu',
       'mathis.thomas.etu', 'matthieu.bouin.etu', 'matthieu.misiak.etu',
       'maxence.magras.etu', 'maxime.mpungwe.etu', 'mayas.bouhadda.etu',
       'mehdi.chaib-deraa.etu', 'mehdi.rabi.etu', 'mehmet.kucukkalfa.etu',
       'mervin.kalistas.etu', 'merwan.sergent.etu',
       'michael.tankeu-bigna.etu', 'milan.caillot.etu',
       'mirdaas-alfa-kaza.alidou.etu', 'mohamed-el-amine.samahri.etu',
       'mohamed-nazim.ait-kaci.etu', 'mohamed-sami.mousaid.etu',
       'mohamed.belfadel.etu', 'mohamed.djafer.etu', 'mohamed.mana.etu',
       'mohamed.trougouty.etu', 'mohamed.zemmouri.etu',
       'mohammed.abdennour.etu', 'momar.niang.etu', 'mounir.achbad.etu',
       'mounir.zebboudji.etu', 'mugisha.nzakamwita.etu',
       'nadjib.zoubir.etu', 'naim.abdellaoui.etu', 'nassim.abbad.etu',
       'nassim.arbaoui.etu', 'nassim.belouar.etu', 'nathan.remoleux.etu',
       'nayad.senaici.etu', 'nayssam.benessalah.etu', 'ndongo.diao.etu',
       None, 'nhungocanh.nguyen.etu', 'nicolas.raharinaivo.etu',
       'nils.charfeddine-barbier.etu', 'noa.gobaut.etu', 'noam.taibi.etu',
       'noe.carpentier.etu', 'noe.le-van-canh-dit-ban.etu',
       'nolan.chevalier.etu', 'nolan.halluin.etu', 'nourou.diouf.etu',
       'oscar.abidi.etu', 'oumou.diallo3.etu', 'oyawa.liza.etu',
       'pap-amath.thiam.etu', 'paul.heroguel.etu',
       'pedro-luis.lock-benites.etu', 'pierre.delecourt.etu',
       'pierrick.cardoso.etu', 'qassim.kahoul.etu',
       'raphael.crozat-moreau.etu', 'raphael.tafani.etu',
       'rayan.fortas.etu', 'rayane.asma.etu', 'rayane.denni.etu',
       'richard.kpande-adzare.etu', 'romain.balitout.etu',
       'romain.faidherbe.etu', 'romain.ruelle.etu', 'romane.deleau.etu',
       'romann.szczepaniak.etu', 'rosche-rostell.batchi-vouala.etu',
       'rose.pananceau.etu', 'ruben.cassin.etu', 'sabine.boukais.etu',
       'sadia.muhammad.etu', 'safa-khawthar.draouche.etu',
       'said.dahmani.etu', 'salem.el-bouhouti.etu', 'salim.rachdi.etu',
       'sami.boumiz.etu', 'sami.mili.etu', 'samir.fandi.etu',
       'samuel.huret.etu', 'samuel.scavone.etu', 'samy.yahia-cherif.etu',
       'serhii.ivkin.etu', 'serigne.cisse.etu',
       'shadrak-arthur.banouanina.etu', 'shema.mugambira.etu',
       'shirel.da-silva.etu', 'sokhna.dia2.etu',
       'taissir.el-hammouchi.etu', 'tarik.amirat.etu',
       'thibault.maton.etu', 'thierno-abdoulaye.diallo2.etu',
       'thierno.barry4.etu', 'thomas.desbuissons.etu',
       'timothe.devigne.etu', 'tristan.melchior.etu',
       'valentin.faust.etu', 'wail.ghouila.etu', 'walid.farrash.etu',
       'waylan.godfrey.etu', 'weeti-sharleen.akogbeto.etu',
       'willy.nguyen.etu', 'yadiradjen.mounien.etu', 'yanis.brahimi.etu',
       'yanis.gannar.etu', 'yanis.kharchi.etu', 'yanis.nabet.etu',
       'yanko.lemoine.etu', 'yasser.jad.etu', 'yastene.chemam.etu',
       'yohan.michel.etu', 'youssef.airaki.etu', 'yves.djegnon.etu',
       'zacharie.deroo.etu'], dtype=object)

In [11]:
df['binom'].unique()

array([None, 'abderrahmen.ayadi.etu', 'hazem.hlioui.etu',
       'serigne.cisse.etu', 'ilian.briki.etu',
       'edohson-arnaud.guedou.etu', 'yasser.jad.etu',
       'nils.charfeddine-barbier.etu', 'nassim.belouar.etu',
       'rayane.denni.etu', 'aissatou-bobo.diallo.etu',
       'fadil.sani-labo.etu', 'anas.rsmouki.etu',
       'romann.szczepaniak.etu', 'mamadou-bachir.barry.etu',
       'sadia.muhammad.etu', 'hajar.amnay.etu', 'nayssam.benessalah.etu',
       'ismail.nejjar.etu', 'bilel.doggui.etu',
       'alpha-abdoulaye.diallo.etu', 'thierno-abdoulaye.diallo2.etu',
       'amine.khadri.etu', 'ghizlane.aissaoui.etu', 'avsin.ata.etu',
       'julien.buseyne.etu', 'igor.belyaev.etu', 'elias.debab.etu',
       'hamza.chebbah.etu', 'clement.sorge.etu', 'antoine.bollen.etu',
       'pierrick.cardoso.etu', 'mayas.bouhadda.etu',
       'safa-khawthar.draouche.etu', 'hugo.vandewalle2.etu',
       'youssef.airaki.etu', 'anass.saidi.etu', 'mohammed.abdennour.etu',
       'nolan.halluin.etu', 'mervin.kalistas.etu', 'boris.mutagoma.etu',
       'asmaa.saibi.etu', 'assia.mousselmal.etu', 'ibrahima.diallo8.etu',
       'imrane.mehenni.etu', 'imane.messali.etu', 'keba.thiam.etu',
       'elyna.belkacemi.etu', 'adama-eliya.avlah.etu',
       'mamadou-sellou.diallo.etu', 'antoine.vanhauwaert.etu',
       'eya.yahyaoui.etu', 'walid.farrash.etu', 'douae.ramdani.etu',
       'mehdi.rabi.etu', 'mohamed-sami.mousaid.etu', 'noa.gobaut.etu',
       'hugo.deschamps2.etu', 'ethan.duhot.etu', 'matthieu.bouin.etu',
       'elyes.guedria.etu', 'sokhna.dia2.etu',
       'jacques-lazare.diatta.etu', 'florian.heyte.etu',
       'elliot.launay.etu', 'jeremie.dhollande.etu', 'anis.medani.etu',
       'sami.mili.etu', 'anas.bouchlaghem.etu', 'nadjib.zoubir.etu',
       'pedro-luis.lock-benites.etu', 'alicia.zouadi.etu',
       'luc.duriez.etu', 'enzo.miuzzo.etu', 'mehdi.chaib-deraa.etu',
       'aymeric.amblanc.etu', 'mounir.achbad.etu', 'abdoulaye.nguere.etu',
       'adam.chikh-touami.etu', 'louis.warembourg.etu',
       'romain.balitout.etu', 'qassim.kahoul.etu',
       'dariya.kinadinova.etu', 'sami.boumiz.etu', 'marion.le-guen.etu',
       'said.dahmani.etu', 'fawaaz.oyedotun.etu', 'enzo.dewez.etu',
       'anaba.hilary-williams.etu', 'mehmet.kucukkalfa.etu',
       'mariama-sere.sylla.etu', 'dantoire-lalle.namoni.etu',
       'yves.djegnon.etu', 'gora.diop.etu', 'kotchi-ange-gedeon.kama.etu',
       'koffi.gantchou.etu', 'samuel.huret.etu', 'yanis.brahimi.etu',
       'amel.hadjloum.etu', 'thomas.desbuissons.etu', 'kilian.graye.etu',
       'thibault.maton.etu', 'manel.kracheni.etu', 'shirel.da-silva.etu',
       'mamadou.diallo9.etu', 'm-bah-ange-pascal.tanoh.etu',
       'paul.heroguel.etu', 'loucas.meganck.etu', 'ahmed.terfas.etu',
       'imad.berhoum.etu', 'enrick.debailleul.etu', 'rayane.asma.etu',
       'naim.abdellaoui.etu', 'samuel.scavone.etu', 'tarik.amirat.etu',
       'mamadou.manga.etu', 'ibrahim.yahia.etu', 'mohamed.mana.etu',
       'nassim.abbad.etu', 'willy.nguyen.etu', 'ahmed.bouziani.etu',
       'florian.casteur-delpierre.etu', 'yanko.lemoine.etu',
       'abdallah.saint-ghislain.etu', 'josselin.hebert.etu',
       'henry.hebelamou.etu', 'shema.mugambira.etu', 'ilyes.hadadi.etu',
       'adame.chairi.etu', 'oumou.diallo3.etu', 'ilyes.benferhat.etu',
       'salim.rachdi.etu', 'alix.carton2.etu', 'pap-amath.thiam.etu',
       'aya.rhani.etu', 'mohamed-el-amine.samahri.etu',
       'faustine.descatoire.etu', 'lea.vannobel.etu',
       'hichame.haddou.etu', 'yastene.chemam.etu',
       'samy.yahia-cherif.etu', 'yanis.nabet.etu', 'manel.cherief.etu',
       'komivi.akpata.etu', 'malak.boudoh-mimun.etu', 'maodo.niang.etu',
       'fatoumata-bintou.traore.etu', 'hadjara.darou.etu',
       'lucile.viau.etu', 'andy.ba.etu', 'nassim.arbaoui.etu',
       'david.kahak.etu', 'noam.taibi.etu', 'noe.carpentier.etu'],
      dtype=object)

In [ ]:
not_matching, index_not_matching = test_preprocessing.test_on_actor(df,'actor')

In [13]:
not_matching

30

In [14]:
index_not_matching

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [ ]:
### Save dataframe in csv file
io_utils.write_csv(df = df, dir = INTERIM_DATA_DIR)

TypeError: write_csv() got an unexpected keyword argument 'dir'

#### Anonymization
Create a new dataframe with three columns : 'actor', 'binom' , 'anonymized_actor'

In [ ]:
anonymized_df = df[['actor', 'binom']].copy() 
anonymized_df['anonymized_actor'] = df.apply(data_anonymization.anonymize_actor, axis=1)

Replace column actor and binom by anonymized_actor

In [ ]:
df[['actor', 'binom']] = df.apply(data_anonymization.anonymize_actor)